<?php

echo "<!DOCTYPE html>\n";
echo "<html lang=\"en\">\n";
echo "<head>\n";
echo "    <meta charset=\"utf-8\">\n";
echo "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n";
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n";
echo "    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\n";
echo "    <meta name=\"description\" content=\"\">\n";
echo "    <meta name=\"author\" content=\"\">\n";
echo "\n";
echo "    <title>Boot Camp</title>\n";
echo "	\n";
echo "	<!--  Font Awesome  -->\n";
echo "	<link href=\"fonts/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\">\n";
echo "	<link href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css\" rel=\"stylesheet\">\n";
echo "	\n";
echo "	<!--  Google Font  -->\n";
echo "	<link href=\"https://fonts.googleapis.com/css?family=Titillium+Web\" rel=\"stylesheet\" type=\"text/css\">\n";
echo "\n";
echo "    <!-- Bootstrap core CSS -->\n";
echo "    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\n";
echo "\n";
echo "    <!-- Custom CSS -->\n";
echo "    <link href=\"css/style.css\" rel=\"stylesheet\">\n";
echo "\n";
echo "\n";
echo "    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\n";
echo "    <!--[if lt IE 9]>\n";
echo "    <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\n";
echo "    <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\n";
echo "    <![endif]-->\n";
echo "</head>\n";
echo "\n";
echo "<body class=\"text-center\">\n";
echo "\n";
echo "    <div class=\"container\">\n";
echo "\n";
echo "        <!--  The justified navigation menu is meant for single line per list item.\n";
echo "        Multiple lines will require custom code not provided by Bootstrap.  -->\n";
echo "        \n";

include 'header.php';

echo "\n";
echo "        <div class=\"jumbotron\">\n";
echo "			<h1>15 week Software Developer Boot Camp</h1>\n";
echo "			<p>This program produces a well-rounded, entry-level software developer.</p>\n";
echo "			<p>The entire program is available online and can be taken from anywhere in the world, with Instructors to help.</p>\n";
echo "			<p>It is composed of 13 courses, each of various length.</p>\n";
echo "			<p>The courses build on one another. Later courses are more advanced and refer back to earlier courses.</p>\n";
echo "			<p>On the Software Developer Boot Camp, students learn almost ten programming languages and it is considered to be one of the most comprehensive coding boot camp curriculums in existence.</p>\n";
echo "			<p>The courses are self-paced and students who study 40 hours a week typically complete the program in 15 weeks. To date, over 95% of all graduates have landed tech jobs.</p>\n";
echo "		</div>\n";
echo "		\n";
echo "\n";
echo "\n";
echo "        <div class=\"panel-group\" id=\"accordion\" role=\"tablist\" aria-multiselectable=\"true\">\n";
echo "		<h1>Full list of courses included in the software developer boot camp:</h1>\n";
echo "          <div class=\"panel panel-default\">\n";
echo "            <div class=\"panel-heading\" role=\"tab\" id=\"headingOne\">\n";
echo "              <h4 class=\"panel-title\">\n";
echo "                <a role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#courseOne\" aria-expanded=\"true\" aria-controls=\"courseOne\">\n";
echo "                    1. Computer Basics Course\n";
echo "                </a>\n";
echo "              </h4>\n";
echo "            </div>\n";
echo "            <div id=\"courseOne\" class=\"panel-collapse collapse in\" role=\"tabpanel\" aria-labelledby=\"courseOne\">\n";
echo "              <div class=\"panel-body\">\n";
echo "                <p>This course is the missing link in effective training in the software field. It contains hundreds of tech definitions written by The Tech Academy. You will gain a comprehensive, solid understanding of nearly every major element of the technology industry, including:</p>\n";
echo "                  <ul class=\"text-left\">\n";
echo "                      <li>Clear definitions for every major technology term</li>\n";
echo "                      <li>Algorithm theory and design</li>\n";
echo "                      <li>Basic machine architecture</li>\n";
echo "                      <li>Central Processing Unit operation</li>\n";
echo "                      <li>Memory operation</li>\n";
echo "                      <li>Fundamentals of creating a computer program</li>\n";
echo "                      <li>Computer network principles</li>\n";
echo "                      <li>Internet design and operation</li>\n";
echo "                      <li>Web browser operation</li>\n";
echo "                      <li>Social Media fundamentals</li>\n";
echo "                      <li>Basic security Concepts</li>\n";
echo "                      <li>And more...</li>\n";
echo "                  </ul>\n";
echo "                  <p><a class=\"btn btn-primary\" href=\"contact.html\" role=\"button\">Apply Now »</a></p>\n";
echo "                  <p><strong>Here is one student success story from the Computer Basics Course:</strong></p>\n";
echo "                  <p>\"With all of the information that I have learned in this course I can use it for a solid foundation. It provides the building blocks to understanding how a computer works on a core level. It will allow me to be more familiar with all the computer terminology that I wasn't very familiar with before. Through taking this course, it actually opened my eyes to the endless possibilities that are available in the software development field. Before I thought web or mobile would be the only places I would want to go, but I have actually grown a curiosity for even OS's or computer software. The course was great, it was nice and easy at the beginning and then went up the ramp in difficulty just right. I loved the challenges that it provided, and I can't wait for more!\" <em>- Jeremiah S.</em></p>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "           \n";
echo "          <div class=\"panel panel-default\">\n";
echo "            <div class=\"panel-heading\" role=\"tab\" id=\"headingOne\">\n";
echo "              <h4 class=\"panel-title\">\n";
echo "                <a role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#courseTwo\" aria-expanded=\"true\" aria-controls=\"courseTwo\">\n";
echo "                    2. WordPress Course\n";
echo "                </a>\n";
echo "              </h4>\n";
echo "            </div>\n";
echo "            <div id=\"courseTwo\" class=\"panel-collapse collapse\" role=\"tabpanel\" aria-labelledby=\"courseTwo\">\n";
echo "              <div class=\"panel-body\">\n";
echo "                <p>This course covers all you will need to know to use WordPress. WordPress is the most widely used Content Management System on Earth. Over 20% of all websites are made using WordPress. You will learn the basics, including:</p>\n";
echo "                  <ul class=\"text-left\">\n";
echo "                      <li>Make your first website</li>\n";
echo "                      <li>Create your own blog</li>\n";
echo "                      <li>What SEO is and how to use it</li>\n";
echo "                      <li>Vital WordPress tips and tricks</li>\n";
echo "                      <li>Using WordPress Widgets & Plugins</li>\n";
echo "                      <li>And more...</li>\n";
echo "                  </ul>\n";
echo "                  <p><a class=\"btn btn-primary\" href=\"contact.html\" role=\"button\">Apply Now »</a></p>\n";
echo "                  <p><strong>Here is one student success story from the WordPress Course:</strong></p>\n";
echo "                  <p>\"I gained a great understanding of the WordPress platform’s robust feature sets and how to create some great sites using plugins.The step by step YouTube video on creating a WordPress website real encompassed a great overview of the WordPress platform and the possibilities of that site. I also learned knowing WordPress is beneficial because 25% of the websites use it as their platform. It is also a great site to develop for because it so user friendly for individuals with limited experience to be able to manage their sites. If I wanted to develop sites for small businesses, the ability for that business owner to manage both their site and their content requires a much lower learning curve than the traditional sites with extensive HTML and limited functionality. WordPress in short is the CMS for the average person. I am already using the tools I learned in this course. My running club has contracted a web developer firm to redesign and build our website using WordPress. The knowledge I learned helped me articulate to my club during one of recent meetings the ability that we can change and update the menus within WordPress, so we would not need to worry about the exact naming of the main level menus as we can change and modify as needed. I can use my knowledge and experience of WordPress to help develop, maintain and teach customers how to use the tools within the system to curate and manage their content.\" <em>- Michael A.</em></p>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "            \n";
echo "          <div class=\"panel panel-default\">\n";
echo "            <div class=\"panel-heading\" role=\"tab\" id=\"headingOne\">\n";
echo "              <h4 class=\"panel-title\">\n";
echo "                <a role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#courseThree\" aria-expanded=\"true\" aria-controls=\"courseThree\">\n";
echo "                    3. Overview of Software Development Course\n";
echo "                </a>\n";
echo "              </h4>\n";
echo "            </div>\n";
echo "            <div id=\"courseThree\" class=\"panel-collapse collapse\" role=\"tabpanel\" aria-labelledby=\"courseThree\">\n";
echo "              <div class=\"panel-body\">\n";
echo "                <p>Here you will learn the basic elements that are fundamental to any computer program, leading to greater comprehension of every computer programming language you will learn in the future. You will have a comprehensive understanding of the basic actions of a Software Developer, including:</p>\n";
echo "                  <ul class=\"text-left\">\n";
echo "                      <li>Object-Oriented Programming basics</li>\n";
echo "                      <li>Web Application basics</li>\n";
echo "                      <li>Database basics</li>\n";
echo "                      <li>What a Software Developer actually does</li>\n";
echo "                      <li>What other skills a Software Developer needs</li>\n";
echo "                      <li>How programs are made in this profession</li>\n";
echo "                      <li>The attitude necessary to be successful</li>\n";
echo "                      <li>How to think like a Computer Programmer</li>\n";
echo "                      <li>Number systems</li>\n";
echo "                      <li>Data structures</li>\n";
echo "                      <li>What Flowcharting is and how it helps you to develop</li>\n";
echo "                      <li>Registry basics</li>\n";
echo "                      <li>Command line basics</li>\n";
echo "                      <li>And more...</li>\n";
echo "                  </ul>\n";
echo "                  <p><a class=\"btn btn-primary\" href=\"contact.html\" role=\"button\">Apply Now »</a></p>\n";
echo "                  <p><strong>Here is one student success story from Overview of Software Development Course:</strong></p>\n";
echo "                  <p>\"I learned the importance of really understanding the basics so that we can think methodically when entering the real world, and even in the rest of this program. For me, I want to further my studying in flowcharting and algorithms so I can really master breaking things down into smaller pieces and have a good base and outline in regards to programming, or at least increased confidence and proficiency in the initial problems to be analyzed and solved. For me, I tend to have a minimal problem asking for help, so this video really encouraged me to ask for it when needed (after I actually try and research and problem solve on my own first). It was also helpful to hear that we do not need to know it all, but rather gain the skills to figure out solutions to problems that arise. This course helped to further drill in my brain a bit more in regards to data types and languages. I can use this information that I have gained in this program so far to remind myself the importance of the basic fundamentals in approaching tough problems that will inevitably arise. Problem solving is the name of the game, after all.\" <em>- Joy E.</em></p>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "            \n";
echo "          <div class=\"panel panel-default\">\n";
echo "            <div class=\"panel-heading\" role=\"tab\" id=\"headingOne\">\n";
echo "              <h4 class=\"panel-title\">\n";
echo "                <a role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#courseFour\" aria-expanded=\"true\" aria-controls=\"courseFour\">\n";
echo "                    4. HTML & CSS Course\n";
echo "                </a>\n";
echo "              </h4>\n";
echo "            </div>\n";
echo "            <div id=\"courseFour\" class=\"panel-collapse collapse\" role=\"tabpanel\" aria-labelledby=\"courseFour\">\n";
echo "              <div class=\"panel-body\">\n";
echo "                <p>This course covers the latest versions of HTML (Hyper Text Markup Language) and CSS (Cascading Style Sheets). All websites are made using HTML. CSS is a tool to manage many elements of the pages made with HTML. You will have a comprehensive understanding of HTML5 & CSS3, including:</p>\n";
echo "                  <ul class=\"text-left\">\n";
echo "                      <li>Making an HTML5 website</li>\n";
echo "                      <li>Customizing it with CSS3</li>\n";
echo "                      <li>Making creative and complex effects</li>\n";
echo "                      <li>All the basic fundamentals of HTML5</li>\n";
echo "                      <li>All the basic fundamentals of CSS3</li>\n";
echo "                      <li>And more...</li>\n";
echo "                  </ul>\n";
echo "                  <p><a class=\"btn btn-primary\" href=\"contact.html\" role=\"button\">Apply Now »</a></p>\n";
echo "                  <p><strong>Here is one student success story from the HTML and CSS Course:</strong></p>\n";
echo "                  <p>\"I am new to the \"modern\" programming languages of the internet, so HTML5 and CSS3 were really new for me at the start of the course. I knew some of the little conventions like inline tags for formatting fonts (like <b>bold</b> or <i>italic</i>), but everything else was 100% new for me. However, it was really simple to pick up. It feels like HTML is a very high level language, truly designed for the human programmer's ease of use and readability instead of the machine.\n";
echo "                      <br />\n";
echo "                      One of the big things that really struck me was how HTML and CSS work with the browsers. I never really put it together in my mind until now, but when we create a website by coding it into HTML and CSS, we are not really \"programming\" per se, but more like giving another program an organized list of instructions to perform on our behalf. While writing HTML code is very, very similar to writing a program, I am not actually writing an executable program. I am writing a \"program\" that is executed by another program (the browser) in order to achieve the results I am looking for. I find that a little fascinating.\n";
echo "                      <br />\n";
echo "                      I know I just talked about how coding HTML is not exactly programming, but that is the most enjoyable thing about the course for me: coding. Learning the syntax of the language and the different uses for each command was really fun. I did several of the exercises in the Murach text which were fun and interesting. It was just following a list of directions, but it gave me a chance to see, in my mind, how one would put these instructions together to achieve desired results. Textbook illustrations and exercises are so academic, but they do help one build upon just head knowledge. I imagine understanding how HTML5 and CSS3 work together and with internet browsers will be quite useful in the future, even if my specific responsibilities may not be in website creation/maintenance. More likely, I will need to read HTML code in order find \"variable\" names used to gather website user inputs in a form for me to then utilize in the creation of another program to process that data.\" <em>-Ryan S.</em></p>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "            \n";
echo "          <div class=\"panel panel-default\">\n";
echo "            <div class=\"panel-heading\" role=\"tab\" id=\"headingOne\">\n";
echo "              <h4 class=\"panel-title\">\n";
echo "                <a role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#courseFive\" aria-expanded=\"true\" aria-controls=\"courseFive\">\n";
echo "                    5. Visual Studio Course\n";
echo "                </a>\n";
echo "              </h4>\n";
echo "            </div>\n";
echo "            <div id=\"courseFive\" class=\"panel-collapse collapse\" role=\"tabpanel\" aria-labelledby=\"courseFive\">\n";
echo "              <div class=\"panel-body\">\n";
echo "                <p>Visual Studio is an Integrated Development Environment from Microsoft that helps you write software programs. It brings together all of the tools you’ll need to make software in one place. Learning to use Visual Studio well will make all of your learning and job duties go faster. You'll cover:</p>\n";
echo "                  <ul class=\"text-left\">\n";
echo "                      <li>Installing Visual Studio</li>\n";
echo "                      <li>Writing code in a programming environment</li>\n";
echo "                      <li>Analyzing your program step-by-step with Visual Studio</li>\n";
echo "                      <li>And more...</li>\n";
echo "                  </ul>\n";
echo "                  <p><a class=\"btn btn-primary\" href=\"contact.html\" role=\"button\">Apply Now »</a></p>\n";
echo "                  <p><strong>Here is a student success story from Visual Studio Course:</strong></p>\n";
echo "                  <p>\"Visual Studio is an Integrated Development Environment IDE) from Microsoft that provides a Graphical User Interface (GUI) for developers to create apps, programs, websites among many other things. It offers developers many programming languages to use including C# and Python. It helps developers write code efficiently through various features like intellisense which anticipates the possible code the developer might use as they type the first few letters and by offering a debugging feature that helps detect and eliminate code errors. As a developer, I imagine using Visual Studio in helping create web apps and web pages. It was good to get an introduction to the Visual Studio environment. I realize it is a very powerful tool that offers a lot more than what I have been introduced to so far.\" <em>- G D.</em></p>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "            \n";
echo "          <div class=\"panel panel-default\">\n";
echo "            <div class=\"panel-heading\" role=\"tab\" id=\"headingOne\">\n";
echo "              <h4 class=\"panel-title\">\n";
echo "                <a role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#courseSix\" aria-expanded=\"true\" aria-controls=\"courseSix\">\n";
echo "                    6. Version Control Course\n";
echo "                </a>\n";
echo "              </h4>\n";
echo "            </div>\n";
echo "            <div id=\"courseSix\" class=\"panel-collapse collapse\" role=\"tabpanel\" aria-labelledby=\"courseSix\">\n";
echo "              <div class=\"panel-body\">\n";
echo "                <p>Keeping track of the various stages of a software program as it is created is vital, if only so that if you find that you’re taking the wrong approach to a programming task, you will want a way to get rid of the changes you made and go back to before you tried that approach. Version control allows this as well as other valuable actions related to managing the sometimes lengthy and complex process of making software. You will learn the various approaches to version control, and use it on your own projects. You'll learn:</p>\n";
echo "                  <ul class=\"text-left\">\n";
echo "                      <li>What source control and version control are</li>\n";
echo "                      <li>Why you must be able to use them</li>\n";
echo "                      <li>How two or hundreds of people can work on the same project at the same time</li>\n";
echo "                      <li>Using version control with the Visual Studio IDE</li>\n";
echo "                      <li>Version control through Team Foundation Server and Git</li>\n";
echo "                      <li>And more...</li>\n";
echo "                  </ul>\n";
echo "                  <p><a class=\"btn btn-primary\" href=\"contact.html\" role=\"button\">Apply Now »</a></p>\n";
echo "                  <p><strong>Here is a student success story from the Version Control Course:</strong></p>\n";
echo "                  <p>\"Version control is managing and tracking changes to a file. In the career of Software Development, It seems that it will be very rare to be working on one file, with only one person touching the file. So tracking the changes of code, managing who is editing and how to merge changes at the same time is critical. Overwriting someones changes or having yours, is the last thing anyone would want. The tools of Git, and other Version Control Systems cover this as well as other tools that help software developers, collaborate to work with each other such as being able to assign tasks and view bug fixes. It seems like all companies are using a version control system, I use one in manufacturing in fact. So you better get familiar with it!\" <em>-Hank B.</em></p>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "            \n";
echo "          <div class=\"panel panel-default\">\n";
echo "            <div class=\"panel-heading\" role=\"tab\" id=\"headingOne\">\n";
echo "              <h4 class=\"panel-title\">\n";
echo "                <a role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#courseSeven\" aria-expanded=\"true\" aria-controls=\"courseSeven\">\n";
echo "                    7. Database and SQL Course\n";
echo "                </a>\n";
echo "              </h4>\n";
echo "            </div>\n";
echo "            <div id=\"courseSeven\" class=\"panel-collapse collapse\" role=\"tabpanel\" aria-labelledby=\"courseSeven\">\n";
echo "              <div class=\"panel-body\">\n";
echo "                <p>A database is an organized collection of data; it can take many forms. A relational database is a database where different types of data are separated from each other, and where the relationships between those types of data are tracked. A RDBMS is a Relational Data Base Management System; it’s a special software program that facilitates the management of one or more relational databases, allowing you to add, read, change and delete data from the database. There exists a specialized programming language used in database operations, called Structured Query Language (SQL). You will learn the principles behind all of these tools, including:</p>\n";
echo "                  <ul class=\"text-left\">\n";
echo "                      <li>Why databases are so important to development</li>\n";
echo "                      <li>Database fundamentals</li>\n";
echo "                      <li>CRUD (Create, Read, Update, Delete) operations</li>\n";
echo "                      <li>How a RDBMS works</li>\n";
echo "                      <li>How databases are used in Web Applications</li>\n";
echo "                      <li>How to create your own database</li>\n";
echo "                      <li>What the Windows Registry is and how to use it</li>\n";
echo "                      <li>What SQL is and how to use it to create and use databases and the data in them</li>\n";
echo "                      <li>And more...</li>\n";
echo "                  </ul>\n";
echo "                  <p><a class=\"btn btn-primary\" href=\"contact.html\" role=\"button\">Apply Now »</a></p>\n";
echo "                  <p><strong>Here is a student success story from Database and SQL Course:</strong></p>\n";
echo "                  <p>\"I gained a lot of information from this course to add to the basic knowledge I had prior to starting. Some of the main things that I learned were combining tables together and how SQL injection works and some of the ways you can prevent it from happening. I will be able to use this information as a developer to create applications that are database driven and construct my database in the correct format. This knowledge will help me a lot whenever I make any applications that are database driven because it showed me how to efficiently construct tables and connect them together using different types of keys. It will also allow me to create secure SQL code so that my application is not vulnerable to being hacked.\" <em>- Jordan R.</em></p>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "            \n";
echo "          <div class=\"panel panel-default\">\n";
echo "            <div class=\"panel-heading\" role=\"tab\" id=\"headingOne\">\n";
echo "              <h4 class=\"panel-title\">\n";
echo "                <a role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#courseEight\" aria-expanded=\"true\" aria-controls=\"courseEight\">\n";
echo "                    8. JavaScript Course\n";
echo "                </a>\n";
echo "              </h4>\n";
echo "            </div>\n";
echo "            <div id=\"courseEight\" class=\"panel-collapse collapse\" role=\"tabpanel\" aria-labelledby=\"courseEight\">\n";
echo "              <div class=\"panel-body\">\n";
echo "                <p>JavaScript is a versatile, popular programming language that is often used to add interactive elements to web pages. It is very much in demand. You will learn the fundamental elements of the JavaScript language, including:</p>\n";
echo "                  <ul class=\"text-left\">\n";
echo "                      <li>History and background of JavaScript</li>\n";
echo "                      <li>Fundamental elements of JavaScript and how to create programs using the language</li>\n";
echo "                      <li>Modifying your web pages using JavaScript</li>\n";
echo "                      <li>Using JavaScript in combination with HTML5 and CSS3 to create dynamic web pages</li>\n";
echo "                      <li>And more...</li>\n";
echo "                  </ul>\n";
echo "                  <p><a class=\"btn btn-primary\" href=\"contact.html\" role=\"button\">Apply Now »</a></p>\n";
echo "                  <p><strong>Here is a student success story from the JavaScript Course:</strong></p>\n";
echo "                  <p>\"The JavaScript course demonstrates the powerful applications of JavaScript and jQuery in web design. As with all of the courses here, it started at a gradual pace that allowed ample time for me to grasp the concept of a new language before embarking upon coding my own JavaScript and jQuery scripts. Each practical embraced a different parameter of this diverse language and broke down the syntax in an easy to understand manner. As intimidating as JavaScript appears at first, I quickly found that it has many similarities to other languages. PHP, (the prerequisite course), for example, really helped to lay the foundation for a lofty amount of the syntax and functions that I encountered in JavaScript. As the course progressed, I felt more and more confident in my JavaScript skills. Even though there were many hours of trial and tribulation, the gratification that I felt when I found the errors in my code and was able to execute a function was empowering. After this course, and all those previous, my understanding and ability to read code has improved exponentially! JavaScript is definitely a powerful tool for every developer to have in their arsenal. Especially in our world of mobile technology and rampant inter-connectivity. The power of JavaScript and the jQuery library is one of the more impressive aspects of this program thus far. To be able to see the level of care and work that is put in by a community of passionate coders to help an already diverse language become more and more applicable across more and more platforms. This course really helped to illustrate the importance of web development languages within the already outstanding curriculum here.\" <em>- Cole D.</em></p>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "            \n";
echo "          <div class=\"panel panel-default\">\n";
echo "            <div class=\"panel-heading\" role=\"tab\" id=\"headingOne\">\n";
echo "              <h4 class=\"panel-title\">\n";
echo "                <a role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#courseNine\" aria-expanded=\"true\" aria-controls=\"courseNine\">\n";
echo "                    9. Python Course\n";
echo "                </a>\n";
echo "              </h4>\n";
echo "            </div>\n";
echo "            <div id=\"courseNine\" class=\"panel-collapse collapse\" role=\"tabpanel\" aria-labelledby=\"courseNine\">\n";
echo "              <div class=\"panel-body\">\n";
echo "                <p>Python is one of the most widely-used programming languages in the world, and is capable of many different types of tasks. Major companies like Google & YouTube use Python. You will learn all of the basic concepts of the language, leading to creating your own programs that can automate complex tasks and repeat them on demand. You’ll learn:</p>\n";
echo "                  <ul class=\"text-left\">\n";
echo "                      <li>Syntax and use of Python version 2.7</li>\n";
echo "                      <li>Syntax and use of Python version 3.4</li>\n";
echo "                      <li>Differences between Python 2 and 3</li>\n";
echo "                      <li>Using Python with Visual Studio</li>\n";
echo "                      <li>Real-world practical exercises</li>\n";
echo "                      <li>And more...</li>\n";
echo "                  </ul>\n";
echo "                  <p><a class=\"btn btn-primary\" href=\"contact.html\" role=\"button\">Apply Now »</a></p>\n";
echo "                  <p><strong>Here is a student success story from the Python Course:</strong></p>\n";
echo "                  <p>\"Python is the first course that's designed to take place over a few weeks. It covers the basics, like variables, functions, and python's basic data structures, all the way up to GUIs and Database manipulation through SQlite. I really enjoyed this course, as someone that loves a programming challenge, this course introduced new concepts by giving students a challenge they may face in the real work place. At first, the script is simple. But each subsequent task requires that the student improve upon the previous script by introducing a new concept. First it's simple file manipulation, then that script is wrapped into a GUI, and finally the GUI is improved and updated with database functionality. By the end, you feel like you've worked on a product that could really be used in a work place on a day to day basis. All the while furthering your knowledge of python. Python is quickly growing into every sector of the LAMP stack these days, and it's a must know for developers planning to work on any area of software development. So being introduced to it in the way The Tech Academy goes about it was a real treat.\" <em>-Nick J.</em></p>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "            \n";
echo "          <div class=\"panel panel-default\">\n";
echo "            <div class=\"panel-heading\" role=\"tab\" id=\"headingOne\">\n";
echo "              <h4 class=\"panel-title\">\n";
echo "                <a role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#courseTen\" aria-expanded=\"true\" aria-controls=\"courseTen\">\n";
echo "                    10. C# Course\n";
echo "                </a>\n";
echo "              </h4>\n";
echo "            </div>\n";
echo "            <div id=\"courseTen\" class=\"panel-collapse collapse\" role=\"tabpanel\" aria-labelledby=\"courseTen\">\n";
echo "              <div class=\"panel-body\">\n";
echo "                <p>C# is a very powerful, mature programming language that can be used to create the most complex and robust of software programs, capable of satisfying the needs of large businesses. It is one of the most in-demand languages in the software development field. You will learn the fundamental elements of this popular language, enabling you to create your own software programs, and getting you well-prepared for your career as a developer. ASP.NET enables a developer to create powerful web applications when working alongside C#. This course includes:</p>\n";
echo "                  <ul class=\"text-left\">\n";
echo "                      <li>The .Net Framework</li>\n";
echo "                      <li>All basic syntax of the C# language and how to use it to implement programming fundamentals</li>\n";
echo "                      <li>Principles of Object-Oriented Programming using C#</li>\n";
echo "                      <li>The ASP.NET Web Application Framework and its model for delivering interactive web sites</li>\n";
echo "                      <li>And more...</li>\n";
echo "                  </ul>\n";
echo "                  <p><a class=\"btn btn-primary\" href=\"contact.html\" role=\"button\">Apply Now »</a></p>\n";
echo "                  <p><strong>Here is a student success story from the C# Course:</strong></p>\n";
echo "                  <p>\"C# was far and away the most intensive course thus far in the program. If you weren't comfortable with programming yet, you certainly will be after taking this course. For me, I took away a solid foundation in C#. Not just syntactically, but in terms of how a C# program should be written. The course really shows you, and demonstrates to you, what exactly an interface is, what an abstract class is, how to use the system libraries, why abstraction is important, and mostly importantly, how to take these concepts and use them to create actual products. In addition to everything above, you'll get a crash course in delegates, lambda functions, ADO.NET and LINQ, how to integrate T-SQL code with your C#, how to handle entities using the Entity Framework, how to work with the various string and file libraries contained within the System libraries. It dives a bit into some basic data structures and algorithms, like queues, and stacks. as well as some basic sorts. All of which is incredibly applicable to the software world, and ultimately are the skills that employers want to see demonstrated to land you a job. The knowledge in this course has prepared me to apply every aspect of Microsoft's frameworks using C#.\" <em>-Nick J.</em></p>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "            \n";
echo "          <div class=\"panel panel-default\">\n";
echo "            <div class=\"panel-heading\" role=\"tab\" id=\"headingOne\">\n";
echo "              <h4 class=\"panel-title\">\n";
echo "                <a role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#courseEleven\" aria-expanded=\"true\" aria-controls=\"courseEleven\">\n";
echo "                    11. Project Management Basics Course\n";
echo "                </a>\n";
echo "              </h4>\n";
echo "            </div>\n";
echo "            <div id=\"courseEleven\" class=\"panel-collapse collapse\" role=\"tabpanel\" aria-labelledby=\"courseEleven\">\n";
echo "              <div class=\"panel-body\">\n";
echo "                <p>The process of building complex software is challenging, and involves the use of special tools and project management procedures in order to achieve a satisfactory outcome. On this course, you will learn the popular project management technologies used in the software development world, including Agile and Scrum. You’ll cover:</p>\n";
echo "                  <ul class=\"text-left\">\n";
echo "                      <li>Project management basics</li>\n";
echo "                      <li>Traditional project management</li>\n";
echo "                      <li>Agile project management principles</li>\n";
echo "                      <li>Scrum fundamentals</li>\n";
echo "                      <li>How to operate as part of a development team</li>\n";
echo "                      <li>And more...</li>\n";
echo "                  </ul>\n";
echo "                  <p><a class=\"btn btn-primary\" href=\"contact.html\" role=\"button\">Apply Now »</a></p>\n";
echo "                  <p><strong>Here is a student success story from the Project Management Basics Course:</strong></p>\n";
echo "                  <p>\"Project Management and the Project Management Life Cycle are specific processes and steps for managing the many tasks, responsibilities, people, and moving parts from project launch to project completion. I think the biggest lessons were not to start a project until you have full agreement on the deliverables and methods for dealing with being behind schedule. The organization that I am interning with is using the Agile methodology, so I am already using that style now. We complete specific tasks in small phases and then turn information over to the client to review. I can see how beneficial it is to operate this way, because it is sometimes simpler to see how something will work rather than have someone explain to you. Interacting with the actual environment gives clients something to provide feedback on.\" <em>- Sara L.</em></p>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "            \n";
echo "          <div class=\"panel panel-default\">\n";
echo "            <div class=\"panel-heading\" role=\"tab\" id=\"headingOne\">\n";
echo "              <h4 class=\"panel-title\">\n";
echo "                <a role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#courseTwelve\" aria-expanded=\"true\" aria-controls=\"courseTwelve\">\n";
echo "                    12. Live Project\n";
echo "                </a>\n";
echo "              </h4>\n";
echo "            </div>\n";
echo "            <div id=\"courseTwelve\" class=\"panel-collapse collapse\" role=\"tabpanel\" aria-labelledby=\"courseTwelve\">\n";
echo "              <div class=\"panel-body\">\n";
echo "                <p>Every student is given the opportunity to partake in an exercise which involves a real world software development project. Our live projects allow a student to put the programming skills they learn to use on practical assignments that mirror actual software development projects one could run across on a real contract. This will be an element of your resume.</p>\n";
echo "                  <p><a class=\"btn btn-primary\" href=\"contact.html\" role=\"button\">Apply Now »</a></p>\n";
echo "                  <p><strong>Here is a student success story from the Live Project:</strong></p>\n";
echo "                  <p>\"Participating in the Live Project was an invaluable learning experience. It has taught me what it’s really like to think and work like a software developer. This experience has helped me to gain a sense of what it may be like to work in a real live software development environment. In this Live Project, I had the opportunity to create raw code that is being used in an actual client’s website. My responsibility was to work with Handlebars.js, a compiler that takes any HTML and Handlebars expression and implements them to a JavaScript function. To be quite frank, I’m still a little unsure of how it completely works. But the important aspect that I drew from this experience is that before the Live Project, I’d never even heard of handlebars.js. But now I can create a webpage that utilizes handlebars.js to a certain degree. This may not seem like much to some with more experience, but to me this is paramount. \n";
echo "                      <br />\n";
echo "                      My greatest computer skill before coming to the Tech Academy was my ability to turn on the computer, which at times I wasn’t very good at that either. I entered the Tech Academy with absolutely no prior computer coding experience. The advances I’ve made through the different courses and completing the Live Project, for me have been huge. I now possess a fundamental ground work of skills that I can use and apply to various aspects of computer programming/development. For that I am very grateful. I can only improve from here!\" <em>- Tony T.</em></p>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "            \n";
echo "          <div class=\"panel panel-default\">\n";
echo "            <div class=\"panel-heading\" role=\"tab\" id=\"headingOne\">\n";
echo "              <h4 class=\"panel-title\">\n";
echo "                <a role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#courseThirteen\" aria-expanded=\"true\" aria-controls=\"courseThirteen\">\n";
echo "                    13. Job Placement Course\n";
echo "                </a>\n";
echo "              </h4>\n";
echo "            </div>\n";
echo "            <div id=\"courseThirteen\" class=\"panel-collapse collapse\" role=\"tabpanel\" aria-labelledby=\"courseThirteen\">\n";
echo "              <div class=\"panel-body\">\n";
echo "                <p>Quite apart from the technical knowledge, we know that the process of getting hired has its own specialized challenges. We’ve put together the hard-won knowledge you’ll need to ensure you’ve got the best possible chance of getting a good job in technology. You’ll learn about:</p>\n";
echo "                  <ul class=\"text-left\">\n";
echo "                      <li>Professional manners and dress</li>\n";
echo "                      <li>Writing a cover letter</li>\n";
echo "                      <li>Writing a resume</li>\n";
echo "                      <li>Preparing for and conducting phone interviews</li>\n";
echo "                      <li>Preparing for and conducting in-person interviews</li>\n";
echo "                      <li>And more...</li>\n";
echo "                  </ul>\n";
echo "                  <p><a class=\"btn btn-primary\" href=\"contact.html\" role=\"button\">Apply Now »</a></p>\n";
echo "                  <p><strong>Here is a student success story from the Job Placement Course:</strong></p>\n";
echo "                  <p>\"I have had previous job placement training, but I think it is really helpful to complete preparation tailored to the field for which you are applying. It always helps my confidence during the job search process to understand what to expect. I am glad to have completed the course at this stage in the process, so that I can be sure to tailor assignments for posting on GitHub to expand my presence online. It is also really helpful to know where to look for jobs. And, I am glad to know about the programming challenge questions. I will definitely be doing a lot of preparation in this area!\" <em>- Sara L.</em></p>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "            \n";
echo "                    <div class=\"panel panel-default\">\n";
echo "            <div class=\"panel-heading\" role=\"tab\" id=\"headingOne\">\n";
echo "              <h4 class=\"panel-title\">\n";
echo "                <a role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#courseOptional\" aria-expanded=\"true\" aria-controls=\"courseOptional\">\n";
echo "                    Optional Courses\n";
echo "                </a>\n";
echo "              </h4>\n";
echo "            </div>\n";
echo "            <div id=\"courseOptional\" class=\"panel-collapse collapse\" role=\"tabpanel\" aria-labelledby=\"courseOptional\">\n";
echo "              <div class=\"panel-body\">\n";
echo "                <p>We have several optional courses that students can take after graduating our Software Developer Boot Camp. Graduates can choose 3 optional courses at no additional cost! In other words, in addition to the 13 courses included in the Software Developer Boot Camp, your tuition includes three optional courses. Here are the optional courses we offer:</p>\n";
echo "                  <ul class=\"text-left\">\n";
echo "                      <li>PHP Course</li>\n";
echo "                      <li>ASP.NET Course</li>\n";
echo "                      <li>Microsoft Technology Associate Examination Preparation Course</li>\n";
echo "                      <li>ASP.NET MVC and vNext Course</li>\n";
echo "                      <li>Advanced JavaScript Course</li>\n";
echo "                      <li>DevOps Course</li>\n";
echo "                      <li>Mobile Development Course</li>\n";
echo "                      <li>CRM Course</li>\n";
echo "                      <li>Hadoop Course</li>\n";
echo "                      <li>Quality Assurance Course</li>\n";
echo "                      <li>SEO Course</li>\n";
echo "                  </ul>\n";
echo "                  <p><a class=\"btn btn-primary\" href=\"contact.html\" role=\"button\">Apply Now »</a></p>\n";
echo "                  \n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "            \n";
echo "        </div>\n";
echo "        \n";
echo "                <div class=\"banner row\">\n";
echo "                <h3>15 week Software Developer Boot Camp</h3>\n";
echo "                <h2><a href=\"contact.html\">Enroll Now and START TODAY</a></h2>\n";
echo "        </div>\n";
echo "    \n";
echo "\n";
echo "    <!--  Site footer  -->\n";

include 'footer.php';

echo "   \n";
echo "\n";
echo "    </div> <!-- /container -->\n";
echo "\n";
echo "    <div id=\"myModalPopUp\" class=\"modal fade\" role=\"dialog\"> <!-- modal dialog box -->\n";
echo "	    <div class=\"modal-dialog\">\n";
echo "		    <!-- Modal content-->\n";
echo "		    <div class=\"modal-content\">\n";
echo "			    <div class=\"modal-header\">\n";
echo "				    <button type=\"button\" class=\"close\" data-dismiss=\"modal\">×</button>\n";
echo "				    <h3 class=\"modal-title\">Hi there!</h3>\n";
echo "			    </div>\n";
echo "			    <div class=\"modal-body\">\n";
echo "				    <p>Would you like to learn more about The Tech Academy?</p>\n";
echo "			    </div>\n";
echo "			    <div class=\"modal-footer\">\n";
echo "                    <a class=\"btn modal-button-yes\" href=\"contact.html\">Yes</a>\n";
echo "                    <a class=\"btn\" data-dismiss=\"modal\">No</a>\n";
echo "			    </div>\n";
echo "		    </div>\n";
echo "	    </div>\n";
echo "    </div>\n";
echo "	\n";
echo "	<!-- Start Alexa Certify Javascript -->\n";
echo "<script type=\"text/javascript\">\n";
echo "_atrk_opts = { atrk_acct:\"jT90m1a8FRh2cN\", domain:\"learncodinganywhere.com\",dynamic: true};\n";
echo "(function() { var as = document.createElement('script'); as.type = 'text/javascript'; as.async = true; as.src = \"https://d31qbv1cthcecs.cloudfront.net/atrk.js\"; var s = document.getElementsByTagName('script')[0];s.parentNode.insertBefore(as, s); })();\n";
echo "</script>\n";
echo "<noscript><img src=\"https://d5nxst8fruw4z.cloudfront.net/atrk.gif?account=jT90m1a8FRh2cN\" style=\"display:none\" height=\"1\" width=\"1\" alt=\"\" /></noscript>\n";
echo "<!-- End Alexa Certify Javascript -->  \n";
echo "\n";
echo "    <script src=\"https://code.jquery.com/jquery-2.1.4.min.js\"></script>\n";
echo "    <script src=\"js/bootstrap.min.js\"></script>\n";
echo "    <script src=\"js/npm.js\"></script>\n";
echo "\n";
echo "    <script>\n";
echo "        $(document).ready(function () {\n";
echo "            function waitThenDoSomething(waitTimeInMS, myAction) {\n";
echo "                setTimeout(function () {\n";
echo "                    if (myAction == \"displayPopup\") {\n";
echo "                        $('#myModalPopUp').modal('show');\n";
echo "                    }\n";
echo "                }, waitTimeInMS); //time in ms to wait before modal dialog box shows up.\n";
echo "            }\n";
echo "            if (document.referrer == \"http://learncodinganywhere.com/index.html\" || document.referrer == \"http://learncodinganywhere.com/\") {\n";
echo "                waitThenDoSomething(0, \"displayPopup\"); //this function waits 0 milliseconds before displaying a popup.\n";
echo "                //I left the wait function here so that if you change your mind and decide you want to wait before showing \n";
echo "                //the modal dialog box, it's as easy as changing the 0 above to a different number, rather than recoding \n";
echo "                //all of it again.\n";
echo "            }\n";
echo "            $(window).ready(function () { $(window).scroll() });\n";
echo "            $(window).scroll(function () {\n";
echo "                $(\".slideanim\").each(function () {\n";
echo "                    var pos = $(this).offset().top;\n";
echo "\n";
echo "                    var winTop = $(window).scrollTop();\n";
echo "\n";
echo "                    if (pos < winTop + $(window).height()) {\n";
echo "                        $(this).addClass(\"slide\");\n";
echo "                    }\n";
echo "                });\n";
echo "            });\n";
echo "        });\n";
echo "    </script>\n";
echo "</body>\n";
echo "</html>\n";

?>

