<?php

echo "<!DOCTYPE html>\n";
echo "<html lang=\"en\">\n";
echo "    <head>\n";
echo "        <meta charset=\"utf-8\">\n";
echo "        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n";
echo "        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n";
echo "        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\n";
echo "        <meta name=\"description\" content=\"\">\n";
echo "        <meta name=\"author\" content=\"\">\n";
echo "\n";
echo "        <title>Employers</title>\n";
echo "	\n";
echo "	    <!--  Font Awesome  -->\n";
echo "	    <link href=\"fonts/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\">\n";
echo "	    <link href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css\" rel=\"stylesheet\">\n";
echo "	\n";
echo "	    <!--  Google Font  -->\n";
echo "	    <link href=\"https://fonts.googleapis.com/css?family=Titillium+Web\" rel=\"stylesheet\" type=\"text/css\">\n";
echo "\n";
echo "        <!-- Bootstrap core CSS -->\n";
echo "        <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\n";
echo "\n";
echo "        <!-- Custom CSS -->\n";
echo "        <link href=\"css/style.css\" rel=\"stylesheet\">\n";
echo "\n";
echo "\n";
echo "        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\n";
echo "        <!--[if lt IE 9]>\n";
echo "        <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\n";
echo "        <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\n";
echo "        <![endif]-->\n";
echo "    </head>\n";
echo "\n";
echo "    <body class=\"text-center\">\n";
echo "\n";
echo "        <!--  The justified navigation menu is meant for single line per list item.\n";
echo "        Multiple lines will require custom code not provided by Bootstrap.  -->\n";
echo "       \n";

include 'header.php';

echo "\n";
echo "        <!-- tiled info -->\n";
echo "        <div>\n";
echo "            <div class=\"row\"><!--  Start Row 1  -->\n";
echo "                <div class=\"col-lg-12  newTiledInfoWhite slideanim\">\n";
echo "                    <p>Please pardon our appearance, this page is still under construction. If you are an employer and would like to contact the school, please click the contact button below.</p>\n";
echo "					<br/>\n";
echo "					<p><a class=\"btn btn-primary btn-lg\" href=\"contact.html\" role=\"button\">Contact</a></p>\n";
echo "				</div>\n";
echo "            </div>\n";
echo "        </div>\n";
echo "        <br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />\n";
echo "        <div class=\"banner row\">\n";
echo "                <h3>15 week Software Developer Boot Camp</h3>\n";
echo "                <h2><a href=\"contact.html\">Enroll Now and START TODAY</a></h2>\n";
echo "        </div>\n";
echo "    \n";
echo "\n";
echo "    <!--  Site footer  -->\n";

include 'footer.php';

echo "    \n";
echo "\n";
echo "        <span itemprop=\"openingHoursSpecification\" itemscope itemtype=\"http://schema.org/OpeningHoursSpecification\">\n";
echo "        <span itemprop=\"dayOfWeek\" itemscope itemtype=\"http://schema.org/DayOfWeek\">\n";
echo "        <meta itemprop=\"name\" content=\"Every day\"></span></span>\n";
echo "        <meta itemprop=\"url\" content=\"http://learncodinganywhere.com/\"></div> <!--  /container  -->\n";
echo "	\n";
echo "	<!-- Start Alexa Certify Javascript -->\n";
echo "<script type=\"text/javascript\">\n";
echo "_atrk_opts = { atrk_acct:\"jT90m1a8FRh2cN\", domain:\"learncodinganywhere.com\",dynamic: true};\n";
echo "(function() { var as = document.createElement('script'); as.type = 'text/javascript'; as.async = true; as.src = \"https://d31qbv1cthcecs.cloudfront.net/atrk.js\"; var s = document.getElementsByTagName('script')[0];s.parentNode.insertBefore(as, s); })();\n";
echo "</script>\n";
echo "<noscript><img src=\"https://d5nxst8fruw4z.cloudfront.net/atrk.gif?account=jT90m1a8FRh2cN\" style=\"display:none\" height=\"1\" width=\"1\" alt=\"\" /></noscript>\n";
echo "<!-- End Alexa Certify Javascript -->  \n";
echo "	\n";
echo "	    <!--  HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries  -->\n";
echo "        <!-- [if lt IE 9]>\n";
echo "        <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\n";
echo "        <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\n";
echo "        <![endif] -->\n";
echo "	    <script async=\"\" src=\"//www.google-analytics.com/analytics.js\"></script><script async=\"\" src=\"//www.google-analytics.com/analytics.js\"></script><script type=\"text/javascript\" async=\"\" src=\"https://d31qbv1cthcecs.cloudfront.net/atrk.js\"></script><script src=\"https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en_US.EUHM0okOSao.O/m=auth/exm=page/rt=j/sv=1/d=1/ed=1/am=AQ/rs=AGLTcCOtX4SuyVD7gCm8N-17I91Nqq-HDQ/t=zcms/cb=gapi.loaded_1\" async=\"\"></script><script src=\"https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en_US.EUHM0okOSao.O/m=page/rt=j/sv=1/d=1/ed=1/am=AQ/rs=AGLTcCOtX4SuyVD7gCm8N-17I91Nqq-HDQ/t=zcms/cb=gapi.loaded_0\" async=\"\"></script><script src=\"https://apis.google.com/js/platform.js\" async=\"\" defer=\"\" gapi_processed=\"true\"></script>\n";
echo "	    <script type=\"text/javascript\"></script><iframe name=\"oauth2relay823781193\" id=\"oauth2relay823781193\" src=\"https://accounts.google.com/o/oauth2/postmessageRelay?parent=http%3A%2F%2Flearncodinganywhere.com#rpctoken=294239902&forcesecure=1\" tabindex=\"-1\" style=\"width: 1px; height: 1px; position: absolute; top: -100px;\"></iframe>\n";
echo "        <noscript><img src=\"https://d5nxst8fruw4z.cloudfront.net/atrk.gif?account=jT90m1a8FRh2cN\" style=\"display:none\" height=\"1\" width=\"1\" alt=\"\" /></noscript>\n";
echo "        <!--  End Alexa Certify Javascript  -->  \n";
echo "        <script></script>\n";
echo "\n";
echo "        <script type=\"text/javascript\" src=\"js/jquery.js\"></script>\n";
echo "        <script type=\"text/javascript\" src=\"js/bootstrap.min.js\"></script>\n";
echo "        <script type=\"text/javascript\" src=\"js/npm.js\"></script>\n";
echo "	    <script>\n";
echo "	        $(document).ready(function () {\n";
echo "                $(window).ready(function () { $(window).scroll() });\n";
echo "		        $(window).scroll(function () {\n";
echo "		            $(\".slideanim\").each(function () {\n";
echo "		                var pos = $(this).offset().top;\n";
echo "\n";
echo "		                var winTop = $(window).scrollTop();\n";
echo "\n";
echo "		                if (pos < winTop + $(window).height()) {\n";
echo "		                    $(this).addClass(\"slide\");\n";
echo "		                }\n";
echo "		            });\n";
echo "		        });\n";
echo "	        });\n";
echo "	    </script>\n";
echo "    </body>\n";
echo "</html>";

?>

