<?php

echo "<!DOCTYPE html>\n";
echo "<html lang=\"en\">\n";
echo "<head>\n";
echo "    <meta charset=\"utf-8\">\n";
echo "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n";
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n";
echo "    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\n";
echo "    <meta name=\"description\" content=\"\">\n";
echo "    <meta name=\"author\" content=\"\">\n";
echo "\n";
echo "    <title>FAQ</title>\n";
echo "	\n";
echo "	<!--  Font Awesome  -->\n";
echo "	<link href=\"fonts/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\">\n";
echo "	<link href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css\" rel=\"stylesheet\">\n";
echo "	\n";
echo "	<!--  Google Font  -->\n";
echo "	<link href=\"https://fonts.googleapis.com/css?family=Titillium+Web\" rel=\"stylesheet\" type=\"text/css\">\n";
echo "\n";
echo "    <!-- Bootstrap core CSS -->\n";
echo "    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\n";
echo "\n";
echo "    <!-- Custom CSS -->\n";
echo "    <link href=\"css/style.css\" rel=\"stylesheet\">\n";
echo "\n";
echo "\n";
echo "    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\n";
echo "    <!--[if lt IE 9]>\n";
echo "    <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\n";
echo "    <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\n";
echo "    <![endif]-->\n";
echo "</head>\n";
echo "\n";
echo "<body class=\"text-center\">\n";
echo "\n";
echo "    <div class=\"container\">\n";
echo "\n";
echo "        <!--  The justified navigation menu is meant for single line per list item.\n";
echo "        Multiple lines will require custom code not provided by Bootstrap.  -->\n";

include 'header.php';

echo "       \n";
echo "        \n";
echo "\n";
echo "\n";
echo "        <div class=\"panel-group\" id=\"accordion\" role=\"tablist\" aria-multiselectable=\"true\">\n";
echo "          <div class=\"panel panel-default\">\n";
echo "            <div class=\"panel-heading\" role=\"tab\" id=\"headingOne\">\n";
echo "              <h4 class=\"panel-title\">\n";
echo "                <a role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#faqOne\" aria-expanded=\"true\" aria-controls=\"faqOne\">\n";
echo "                    What is a code school and what is a programming boot camp?\n";
echo "                </a>\n";
echo "              </h4>\n";
echo "            </div>\n";
echo "            <div id=\"faqOne\" class=\"panel-collapse collapse in\" role=\"tabpanel\" aria-labelledby=\"faqOne\">\n";
echo "              <div class=\"panel-body\">\n";
echo "                <p>A programming boot camp, also commonly called a “developer boot camp” or “coding boot camp”, is an intensive training program in software development. A code school is an entity that delivers a dev boot camp.</p>\n";
echo "                <p>Jack Stanley and Erik Gross, the Co-Founders of The Tech Academy actually wrote an article that covers this subject. The article can be found here: <a href=\"http://blog.learncodinganywhere.com/post/what-is-a-code-school\" target=\"_blank\">http://blog.learncodinganywhere.com/post/what-is-a-code-school</a></p>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "            \n";
echo "          <div class=\"panel panel-default\">\n";
echo "            <div class=\"panel-heading\" role=\"tab\" id=\"headingTwo\">\n";
echo "              <h4 class=\"panel-title\">\n";
echo "                <a class=\"collapsed\" role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#faqTwo\" aria-expanded=\"false\" aria-controls=\"faqTwo\">\n";
echo "                  There are so many coding boot camp programs out there, how do I choose one school to attend?\n";
echo "                </a>\n";
echo "              </h4>\n";
echo "            </div>\n";
echo "            <div id=\"faqTwo\" class=\"panel-collapse collapse\" role=\"tabpanel\" aria-labelledby=\"headingTwo\">\n";
echo "              <div class=\"panel-body\">\n";
echo "                  <p>This ultimately depends on what your end goal is. To fully answer this question, Jack Stanley and Erik Gross (the Co-Founders of The Tech Academy) wrote an article entitled \"Which Code School is the Best?\". This article can be found here: <a href=\"http://blog.learncodinganywhere.com/post/which-code-school-is-the-best\" target=\"_blank\">http://blog.learncodinganywhere.com/post/which-code-school-is-the-best</a></p>\n";
echo "                  <p>For additional data, please check out another article written by Mr. Stanley and Mr. Gross, entitled \"What is a Code School?\", found here: <a href=\"http://blog.learncodinganywhere.com/post/what-is-a-code-school\" target=\"_blank\">http://blog.learncodinganywhere.com/post/what-is-a-code-school</a></p>\n";
echo "                <p>Both of the above articles provide advice on how to approach one's search for the right program.</p>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "            \n";
echo "          <div class=\"panel panel-default\">\n";
echo "            <div class=\"panel-heading\" role=\"tab\" id=\"headingThree\">\n";
echo "              <h4 class=\"panel-title\">\n";
echo "                <a class=\"collapsed\" role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#faqThree\" aria-expanded=\"false\" aria-controls=\"faqThree\">\n";
echo "                  How long has The Tech Academy been around?\n";
echo "                </a>\n";
echo "              </h4>\n";
echo "            </div>\n";
echo "            <div id=\"faqThree\" class=\"panel-collapse collapse\" role=\"tabpanel\" aria-labelledby=\"headingThree\">\n";
echo "              <div class=\"panel-body\">\n";
echo "                <p>The short answer: since 2012.</p>\n";
echo "                <p>Erik (Co-Founder of The Tech Academy) has been training developers for over ten years. In 2012, he decided to launch his own programming boot camp under the name \"Prosper I.T. Academy\". The program has been running since then.</p>\n";
echo "                <p>At the end of 2013, Erik brought on Jack Stanley. They spent months on curriculum development and in early 2014, re-branded as The Tech Academy because based on suryeys done, The Tech Academy was a better name.</p>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "            \n";
echo "          <div class=\"panel panel-default\">\n";
echo "            <div class=\"panel-heading\" role=\"tab\" id=\"headingThree\">\n";
echo "              <h4 class=\"panel-title\">\n";
echo "                <a class=\"collapsed\" role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#faqFour\" aria-expanded=\"false\" aria-controls=\"faqFour\">\n";
echo "                  When can I enroll?\n";
echo "                </a>\n";
echo "              </h4>\n";
echo "            </div>\n";
echo "            <div id=\"faqFour\" class=\"panel-collapse collapse\" role=\"tabpanel\" aria-labelledby=\"headingFour\">\n";
echo "              <div class=\"panel-body\">\n";
echo "                <p>Anytime. We don’t have set class dates like “must enroll by June 12th\" or anything of the sort. We allow students to start our program at a time/date that is best for them.</p>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "\n";
echo "        <div class=\"panel panel-default\">\n";
echo "            <div class=\"panel-heading\" role=\"tab\" id=\"headingThree\">\n";
echo "              <h4 class=\"panel-title\">\n";
echo "                <a class=\"collapsed\" role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#faqFive\" aria-expanded=\"false\" aria-controls=\"faqFive\">\n";
echo "                  What is the schedule of the program?\n";
echo "                </a>\n";
echo "              </h4>\n";
echo "            </div>\n";
echo "            <div id=\"faqFive\" class=\"panel-collapse collapse\" role=\"tabpanel\" aria-labelledby=\"headingFive\">\n";
echo "              <div class=\"panel-body\">\n";
echo "                <p>Our program is self-paced. We are open weekdays, weeknights and weekends. We recommend students study a minimum of 40 hours a week at our school because this best guarantees they will complete their training within the normal time period. But, 40 hours a week is not required. We are flexible. Some students work full-time concurrently to taking our program, so they work on our program part-time; maybe 20 hours a week. We work with students so that they can study on a schedule that is most convenient for them.</p>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "        \n";
echo "          <div class=\"panel panel-default\">\n";
echo "            <div class=\"panel-heading\" role=\"tab\" id=\"headingThree\">\n";
echo "              <h4 class=\"panel-title\">\n";
echo "                <a class=\"collapsed\" role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#faqSix\" aria-expanded=\"false\" aria-controls=\"faqSix\">\n";
echo "                  How much does it cost?\n";
echo "                </a>\n";
echo "              </h4>\n";
echo "            </div>\n";
echo "            <div id=\"faqSix\" class=\"panel-collapse collapse\" role=\"tabpanel\" aria-labelledby=\"headingSix\">\n";
echo "              <div class=\"panel-body\">\n";
echo "                <p>We currently are offering a discount on the Software Developer Boot Camp - the price is $7,980. This discount lasts until May 1, 2016, at which point our pricing will be reevaluated and most likely increased. The full price for the Software Developer Boot Camp is $10,000. </p>\n";
echo "                    <p>In short, if a student pays their tuition in full by May 1, the Software Developer Boot Camp costs $7,980.</p>\n";
echo "				<p class=\"scholarship\">In addition to our discounted tuition price, we are also offering a $1000 scholarship for any student that can commit to studying at least 40 hours per week. In effect, the new tuition price would be brought down to $6,980 This scholarship should be taken advantage of quickly as there are a limited number offered.</p>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "            \n";
echo "          <div class=\"panel panel-default\">\n";
echo "            <div class=\"panel-heading\" role=\"tab\" id=\"headingThree\">\n";
echo "              <h4 class=\"panel-title\">\n";
echo "                <a class=\"collapsed\" role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#faqSeven\" aria-expanded=\"false\" aria-controls=\"faqSeven\">\n";
echo "                  Can I study from home or take the program remotely?\n";
echo "                </a>\n";
echo "              </h4>\n";
echo "            </div>\n";
echo "            <div id=\"faqSeven\" class=\"panel-collapse collapse\" role=\"tabpanel\" aria-labelledby=\"headingSeven\">\n";
echo "              <div class=\"panel-body\">\n";
echo "                <p>In short, yes.</p>\n";
echo "                <p>We are able to deliver our entire program remotely. The full Software Developer Boot Camp is available online and can be accessed from anywhere in the world.\n";
echo "A majority of our student body takes the program from home, with Instructors in Portland available during work hours to help.</p>\n";
echo "                <p>Student who live in Oregon attend the boot camp in at or Portland campus, in person.</p>\n";
echo "                <p>If a student has a choice between taking the program remotely (from home) or coming into the campus to take the program in person, we recommend the latter (coming to the school to student in person).</p>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "          \n";
echo "          <div class=\"panel panel-default\">\n";
echo "            <div class=\"panel-heading\" role=\"tab\" id=\"headingThree\">\n";
echo "              <h4 class=\"panel-title\">\n";
echo "                <a class=\"collapsed\" role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#faqEight\" aria-expanded=\"false\" aria-controls=\"faqEight\">\n";
echo "                  Are there any discounts or scholarships available?\n";
echo "                </a>\n";
echo "              </h4>\n";
echo "            </div>\n";
echo "            <div id=\"faqEight\" class=\"panel-collapse collapse\" role=\"tabpanel\" aria-labelledby=\"headingEight\">\n";
echo "              <div class=\"panel-body\">\n";
echo "                <p>For the Software Developer Boot Camp, the full price is $10,000. However, if a student pays the full tuition up front before May 1st, we give a $2,020 discount - bringing the price to $7,980. We offer group discounts for companies who pay for training multiple employees at once through our school. </p>\n";
echo "				<p class=\"scholarship\">As a special offer, any student that can commit to studying at least 40 hours per week will receive a $1000 scholarship making the new price $6980. This scholarship is subject to discontinuation without prior notice.</p>\n";
echo "                <p>We also offer customized curriculums for companies, nonprofit organizations and governmental agencies who are looking to train multiple people at our Academy.</p>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "\n";
echo "          <div class=\"panel panel-default\">\n";
echo "            <div class=\"panel-heading\" role=\"tab\" id=\"headingThree\">\n";
echo "              <h4 class=\"panel-title\">\n";
echo "                <a class=\"collapsed\" role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#faqNine\" aria-expanded=\"false\" aria-controls=\"faqNine\">\n";
echo "                  What is your curriculum based on?\n";
echo "                </a>\n";
echo "              </h4>\n";
echo "            </div>\n";
echo "            <div id=\"faqNine\" class=\"panel-collapse collapse\" role=\"tabpanel\" aria-labelledby=\"headingNine\">\n";
echo "              <div class=\"panel-body\">\n";
echo "                <p>The curriculum was created by several people, but was mainly developed by the founder (Mr. Erik Gross) and co-founder of The Tech Academy (Mr. Jack Stanley).</p>\n";
echo "                <p>The curriculum has been reviewed and signed off on by multiple individuals with degrees in Computer Science and covers all basic information necessary to create a competent junior developer. Those who have assisted in our curriculum development total to over 100 combined years of experience in IT.</p>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "            \n";
echo "          <div class=\"panel panel-default\">\n";
echo "            <div class=\"panel-heading\" role=\"tab\" id=\"headingThree\">\n";
echo "              <h4 class=\"panel-title\">\n";
echo "                <a class=\"collapsed\" role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#faqTen\" aria-expanded=\"false\" aria-controls=\"faqTen\">\n";
echo "                  What are your payment options?\n";
echo "                </a>\n";
echo "              </h4>\n";
echo "            </div>\n";
echo "            <div id=\"faqTen\" class=\"panel-collapse collapse\" role=\"tabpanel\" aria-labelledby=\"headingTen\">\n";
echo "              <div class=\"panel-body\">\n";
echo "                <p>Our tuition pricing is as follows:</p><br/>\n";
echo "                <p>FULL PRICE: $10,000</p><br/>\n";
echo "                <p>PAID UP FRONT: $7980 ($2,020 discount)</p><br/>\n";
echo "				<p>PAID IN TWO PAYMENTS: $4,490 downpayment and $4,490 at the 10 week mark ($8,980 total - $1,020 discount)\n";
echo "				</p><br/>\n";
echo "                <p>ASK ABOUT OUR FINANCING OPTIONS!</p><br/>\n";
echo "				<p class=\"scholarship\">SCHOLARSHIP: A $1000 scholarship will be awarded to any student that will commit to studying 40 hours each week. Meaning, those who can study 40 hours a week pay either:\n";
echo "				a. $6,980 up front or b. $7,980 in two payments. No scholarship for financing.</p>\n";
echo "				\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "            \n";
echo "          <div class=\"panel panel-default\">\n";
echo "            <div class=\"panel-heading\" role=\"tab\" id=\"headingThree\">\n";
echo "              <h4 class=\"panel-title\">\n";
echo "                <a class=\"collapsed\" role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#faqEleven\" aria-expanded=\"false\" aria-controls=\"faqEleven\">\n";
echo "                  Can I do the Boot Camp online?\n";
echo "                </a>\n";
echo "              </h4>\n";
echo "            </div>\n";
echo "            <div id=\"faqEleven\" class=\"panel-collapse collapse\" role=\"tabpanel\" aria-labelledby=\"headingEleven\">\n";
echo "              <div class=\"panel-body\">\n";
echo "                <p>Yes, our program is available in full online. Our Instructors are available over the phone, email, Skype, etc. to assist students through course by\n";
echo "course. The Software Developer Boot Camp can be done anywhere.</p>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "            \n";
echo "          <div class=\"panel panel-default\">\n";
echo "            <div class=\"panel-heading\" role=\"tab\" id=\"headingThree\">\n";
echo "              <h4 class=\"panel-title\">\n";
echo "                <a class=\"collapsed\" role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#faqTwelve\" aria-expanded=\"false\" aria-controls=\"faqTwelve\">\n";
echo "                  Do you offer paired programming?\n";
echo "                </a>\n";
echo "              </h4>\n";
echo "            </div>\n";
echo "            <div id=\"faqTwelve\" class=\"panel-collapse collapse\" role=\"tabpanel\" aria-labelledby=\"headingTwelve\">\n";
echo "              <div class=\"panel-body\">\n";
echo "                <p>Our program is a balance of theory study and practical experience. Throughout the Boot Camp, you will be assigned paired coding projects\n";
echo "occasionally. So the answer is: yes, sometimes you will be paired and sometimes you will work solo - just like the real world.</p>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "            \n";
echo "          <div class=\"panel panel-default\">\n";
echo "            <div class=\"panel-heading\" role=\"tab\" id=\"headingThree\">\n";
echo "              <h4 class=\"panel-title\">\n";
echo "                <a class=\"collapsed\" role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#faqThirteen\" aria-expanded=\"false\" aria-controls=\"faqThirteen\">\n";
echo "                  How is it that The Tech Academy can maintain a 95% job placement rate?\n";
echo "                </a>\n";
echo "              </h4>\n";
echo "            </div>\n";
echo "            <div id=\"faqThirteen\" class=\"panel-collapse collapse\" role=\"tabpanel\" aria-labelledby=\"headingThirteen\">\n";
echo "              <div class=\"panel-body\">\n";
echo "                <p>1. There are Job Placement Directors at The Tech Academy whose sole job is to assist students and graduates in their job search.<br />\n";
echo "                    2. The final course of the Software Developer Boot Camp is the Job Placement Course. This course teaches people all they need to know to get\n";
echo "a job in technology.</p>\n";
echo "                <p>We work hard to ensure that every graduate lands a job.</p>\n";
echo "                <p>At the end of the day, we can't get a job for students, so the 95% placement rate is really the product of persistence on the part of students and\n";
echo "graduates of our program.</p>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "            \n";
echo "          <div class=\"panel panel-default\">\n";
echo "            <div class=\"panel-heading\" role=\"tab\" id=\"headingThree\">\n";
echo "              <h4 class=\"panel-title\">\n";
echo "                <a class=\"collapsed\" role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#faqFourteen\" aria-expanded=\"false\" aria-controls=\"faqFourteen\">\n";
echo "                  Are you accredited?\n";
echo "                </a>\n";
echo "              </h4>\n";
echo "            </div>\n";
echo "            <div id=\"faqFourteen\" class=\"panel-collapse collapse\" role=\"tabpanel\" aria-labelledby=\"headingFourteen\">\n";
echo "              <div class=\"panel-body\">\n";
echo "                <p>Accreditation is a long process, sometimes taking some schools years to complete. As of right now, we are not accredited but we have begun the\n";
echo "application process and hope to achieve accreditation in the near future.</p>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "            \n";
echo "          <div class=\"panel panel-default\">\n";
echo "            <div class=\"panel-heading\" role=\"tab\" id=\"headingThree\">\n";
echo "              <h4 class=\"panel-title\">\n";
echo "                <a class=\"collapsed\" role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#faqFifteen\" aria-expanded=\"false\" aria-controls=\"faqFifteen\">\n";
echo "                  What certification do you offer?\n";
echo "                </a>\n";
echo "              </h4>\n";
echo "            </div>\n";
echo "            <div id=\"faqFifteen\" class=\"panel-collapse collapse\" role=\"tabpanel\" aria-labelledby=\"headingFifteen\">\n";
echo "              <div class=\"panel-body\">\n";
echo "                <p>We offer an optional course that prepares students to take the the MTA exam through Microsoft which certifies them as a Microsoft Technology\n";
echo "Associate. </p>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "        \n";
echo "          <div class=\"panel panel-default\">\n";
echo "            <div class=\"panel-heading\" role=\"tab\" id=\"headingThree\">\n";
echo "              <h4 class=\"panel-title\">\n";
echo "                <a class=\"collapsed\" role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#faqSixteen\" aria-expanded=\"false\" aria-controls=\"faqSixteen\">\n";
echo "                  Do you offer any sort of referral program?\n";
echo "                </a>\n";
echo "              </h4>\n";
echo "            </div>\n";
echo "            <div id=\"faqSixteen\" class=\"panel-collapse collapse\" role=\"tabpanel\" aria-labelledby=\"headingSixteen\">\n";
echo "              <div class=\"panel-body\">\n";
echo "                <p>We do offer commissions for referrals. Email us to find out about our referral program.</p>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "            \n";
echo "        </div>\n";
echo "        <div class=\"slideanim\">\n";
echo "            <p>Again, if you have further questions that weren’t covered above, please feel free to <a href=\"contact.html\">contact us</a>.</p>\n";
echo "            <p>Also, here is a video that explains our program and answers common questions:</p>\n";
echo "            <iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/goznrmb5gls\" id=\"iframeOtherPages\" frameborder=\"0\" allowfullscreen></iframe>\n";
echo "        </div>\n";
echo "        \n";
echo "        <div class=\"banner row\">\n";
echo "                <h3>15 week Software Developer Boot Camp</h3>\n";
echo "                <h2><a href=\"contact.html\">Enroll Now and START TODAY</a></h2>\n";
echo "        </div>\n";
echo "    \n";

include 'footer.php';

echo "\n";
echo "   \n";
echo "    </div> <!-- /container -->\n";
echo "    <div id=\"myModalPopUp\" class=\"modal fade\" role=\"dialog\"> <!-- modal dialog box -->\n";
echo "	    <div class=\"modal-dialog\">\n";
echo "		    <!-- Modal content-->\n";
echo "		    <div class=\"modal-content\">\n";
echo "			    <div class=\"modal-header\">\n";
echo "				    <button type=\"button\" class=\"close\" data-dismiss=\"modal\">×</button>\n";
echo "				    <h3 class=\"modal-title\">Hi there!</h3>\n";
echo "			    </div>\n";
echo "			    <div class=\"modal-body\">\n";
echo "				    <p>Would you like to learn more about The Tech Academy?</p>\n";
echo "			    </div>\n";
echo "			    <div class=\"modal-footer\">\n";
echo "                    <a class=\"btn modal-button-yes\" href=\"contact.html\">Yes</a>\n";
echo "                    <a class=\"btn\" data-dismiss=\"modal\">No</a>\n";
echo "			    </div>\n";
echo "		    </div>\n";
echo "	    </div>\n";
echo "    </div>\n";
echo "	\n";

echo "	<!-- Start Alexa Certify Javascript -->\n";
echo "<script type=\"text/javascript\">\n";
echo "_atrk_opts = { atrk_acct:\"jT90m1a8FRh2cN\", domain:\"learncodinganywhere.com\",dynamic: true};\n";
echo "(function() { var as = document.createElement('script'); as.type = 'text/javascript'; as.async = true; as.src = \"https://d31qbv1cthcecs.cloudfront.net/atrk.js\"; var s = document.getElementsByTagName('script')[0];s.parentNode.insertBefore(as, s); })();\n";
echo "</script>\n";
echo "\n";
echo "<noscript><img src=\"https://d5nxst8fruw4z.cloudfront.net/atrk.gif?account=jT90m1a8FRh2cN\" style=\"display:none\" height=\"1\" width=\"1\" alt=\"\" /></noscript>\n";
echo "<!-- End Alexa Certify Javascript -->   \n";
echo "\n";
echo "    <script src=\"https://code.jquery.com/jquery-2.1.4.min.js\"></script>\n";
echo "    <script src=\"js/bootstrap.min.js\"></script>\n";
echo "    <script src=\"js/npm.js\"></script>\n";
echo "\n";
echo "    <script>\n";
echo "        $(document).ready(function () {\n";
echo "            function waitThenDoSomething(waitTimeInMS, myAction) {\n";
echo "                setTimeout(function () {\n";
echo "                    if (myAction == \"displayPopup\") {\n";
echo "                        $('#myModalPopUp').modal('show');\n";
echo "                    }\n";
echo "                }, waitTimeInMS); //time in ms to wait before modal dialog box shows up.\n";
echo "            }\n";
echo "            if (document.referrer == \"http://learncodinganywhere.com/index.html\" || document.referrer == \"http://learncodinganywhere.com/\") {\n";
echo "                waitThenDoSomething(0, \"displayPopup\"); //this function waits 0 milliseconds before displaying a popup.\n";
echo "                //I left the wait function here so that if you change your mind and decide you want to wait before showing \n";
echo "                //the modal dialog box, it's as easy as changing the 0 above to a different number, rather than recoding \n";
echo "                //all of it again.\n";
echo "            }\n";
echo "            $(window).ready(function () { $(window).scroll() });\n";
echo "            $(window).scroll(function () {\n";
echo "                $(\".slideanim\").each(function () {\n";
echo "                    var pos = $(this).offset().top;\n";
echo "\n";
echo "                    var winTop = $(window).scrollTop();\n";
echo "\n";
echo "                    if (pos < winTop + $(window).height()) {\n";
echo "                        $(this).addClass(\"slide\");\n";
echo "                    }\n";
echo "                });\n";
echo "            });\n";
echo "        });\n";
echo "    </script>\n";

echo "</body>\n";
echo "</html>\n";

?>

