<?php

echo "<!DOCTYPE html>\n";
echo "<html lang=\"en\">\n";
echo "<head>\n";
echo "    <meta charset=\"utf-8\">\n";
echo "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n";
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n";
echo "    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\n";
echo "    <meta name=\"description\" content=\"\">\n";
echo "    <meta name=\"author\" content=\"\">\n";
echo "\n";
echo "    <title>Staff</title>\n";
echo "	\n";
echo "	<!--  Font Awesome  -->\n";
echo "	<link href=\"fonts/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\">\n";
echo "	<link href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css\" rel=\"stylesheet\">\n";
echo "	\n";
echo "	<!--  Google Font  -->\n";
echo "	<link href=\"https://fonts.googleapis.com/css?family=Titillium+Web\" rel=\"stylesheet\" type=\"text/css\">\n";
echo "\n";
echo "    <!-- Bootstrap core CSS -->\n";
echo "    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\n";
echo "\n";
echo "    <!-- Custom CSS -->\n";
echo "    <link href=\"css/style.css\" rel=\"stylesheet\">\n";
echo "\n";
echo "\n";
echo "    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\n";
echo "    <!--[if lt IE 9]>\n";
echo "    <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\n";
echo "    <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\n";
echo "    <![endif]-->\n";
echo "</head>\n";
echo "\n";
echo "<body class=\"text-center\">\n";
echo "\n";
echo "    <div class=\"container\">\n";
echo "\n";
echo "        <!--  The justified navigation menu is meant for single line per list item.\n";
echo "        Multiple lines will require custom code not provided by Bootstrap.  -->\n";
echo "        \n";

include 'header.php';

echo "\n";
echo "        <!-- Jumbotron -->\n";
echo "        <div class=\"jumbotron\">\n";
echo "            <h1>The Tech Academy's Staff</h1>\n";
echo "            <img src=\"images/staff.jpg\" class=\"img_fit\"/>\n";
echo "        </div>\n";
echo "        \n";
echo "        \n";
echo "        <!-- Start Tiles -->\n";
echo "        <div class=\"row tiles\"><!-- Start Row 1 -->\n";
echo "            <div class=\"col-lg-6 slideanim\">\n";
echo "                <img src=\"images/ERIC_1.jpg\" />\n";
echo "                <p class=\"lead\">Erik Gross<br />Co-Founder</p>\n";
echo "                <p>Erik Gross is a skilled .NET developer, consultant and mentor with many years of experience in the Portland I.T. community. Erik’s technology career began in the U.S. Navy, as an Electronics Technician First Class. He worked aboard nuclear-powered ships, operating and maintaining the nuclear power plant. He also taught computer theory, electronics, physics, chemistry and more to incoming Nuclear Power trainees. Erik has worked as a manager, business owner, consultant, writer and software developer. With over thirty years of technology work under his belt and a passion for teaching, he is well qualified to train software developers.\n";
echo "</p>\n";
echo "            </div>\n";
echo "            <div class=\"col-lg-6 slideanim\">\n";
echo "                <img src=\"images/JACK_1.jpg\" />\n";
echo "                <p class=\"lead\">Jack Stanley<br />Co-Founder</p>\n";
echo "                <p>Jack Stanley is a young entrepreneur with more almost 15 years of experience in the executive arena. Prior to working at The Tech Academy, he ran two successful small businesses in Portland. He made his way to The Tech Academy as Erik’s top choice for a business partner. Jack has a background in teaching, business consultation, HR, recruitment, public relations, marketing, legal management, personnel, contracts and licenses, quality control, sales and management, and he is certified in several areas. With his background in educating and successful experience in running companies, Jack complements Erik’s technical skill.</p>\n";
echo "            </div>\n";
echo "        </div><!-- End Row 1 -->\n";
echo "        \n";
echo "        <div class=\"row tiles\"><!-- Start Row 2 -->\n";
echo "            <div class=\"col-lg-4 slideanim\">\n";
echo "                <img src=\"images/TONY_3.jpg\" />\n";
echo "                <p class=\"lead\">Tony Thach<br />Lead Instructor</p>\n";
echo "                <p>Tony has a background in I.T. in addition to going through the Software Developer Boot Camp. He is skilled in all the programming languages we teach and so he was placed as one of the Lead Instructors to ensure our quality of instruction stays high. He is a very dynamic individual and really cares about helping people succeed in life.\n";
echo "</p>\n";
echo "            </div>\n";
echo "            <div class=\"col-lg-4 slideanim\">\n";
echo "                <img src=\"images/EMILY_1.jpg\" />\n";
echo "                <p class=\"lead\">Emily Hayes<br />Accounting Manager</p>\n";
echo "                <p>With a background in accounting with a major American corporation, Emily joined our team and handles all the Tech Academy’s financial matters. She is also studying the Software Developer Boot Camp in her spare time and she’s a bright addition to our team. Emily also assists with students occasionally to ensure they smoothly progress through the bootcamp.\n";
echo "</p>\n";
echo "            </div>\n";
echo "            <div class=\"col-lg-4 slideanim\">\n";
echo "                <img src=\"images/BRETT_2.jpg\" />\n";
echo "                <p class=\"lead\">Brett Caudle<br />Student Registration</p>\n";
echo "                <p>Brett was the first official graduate of The Tech Academy’s Software Developer Bootcamp. He has an extensive background in teaching and education. The first position Brett held was that of Instructor, but he has since moved onto student registration and is a great asset in that area. Brett is well-qualified to answer all prospective student questions.\n";
echo "</p>\n";
echo "            </div>\n";
echo "        </div><!-- End Row 2 -->\n";
echo "        \n";
echo "        <div class=\"row tiles\"><!-- Start Row 3 -->\n";
echo "            <div class=\"col-lg-4 slideanim\">\n";
echo "                <img src=\"images/KENDRA_1.jpg\" />\n";
echo "                <p class=\"lead\">Kendra<br />Student Care Director</p>\n";
echo "                <p>Kendra was brought on as an Instructor for her bright and friendly personality. She has skills in several programming languages and a variety of web technologies.</p>\n";
echo "            </div>\n";
echo "            <div class=\"col-lg-4 slideanim\">\n";
echo "                <img src=\"images/ADAM_1.jpg\" />\n";
echo "                <p class=\"lead\">Adam<br />Senior Instructor</p>\n";
echo "                <p>Adam is the top Instructor in the school and oversees all other Instructors. He has years of experience as an executive and is a graduate of the Software Developer Boot Camp. Adam’s experience in administration and technology makes him the perfect fit as our Senior Instructor.</p>\n";
echo "            </div>\n";
echo "            <div class=\"col-lg-4 slideanim\">\n";
echo "                <img src=\"images/BROOK_1.jpg\" />\n";
echo "                <p class=\"lead\">Brook<br />Instructor</p>\n";
echo "                <p>Brook is a talented programmer and does well with encouraging others and assisting students through our program. When it comes to programming. He is an educated, intelligent individual and a skilled Instructor.</p>\n";
echo "            </div>\n";
echo "        </div><!-- End Row 3 -->\n";
echo "        \n";
echo "        <div class=\"row tiles\"><!-- Start Row 4 -->\n";
echo "            <div class=\"col-lg-4 slideanim\">\n";
echo "                <!--<img src=\"images/\" />-->\n";
echo "                <p class=\"lead\">Cliff<br />Live Project In-Charge</p>\n";
echo "                <p>As a graduate of the Software Developer Boot Camp and someone who worked extensively with Prosper I.T. Consulting, Cliff was the best choice to hold our Live Project In-Charge position. As the Live Project I/C, Cliff runs students through real-world contracts during their 2 week live project at the school</p>\n";
echo "            </div>\n";
echo "            <div class=\"col-lg-4 slideanim\">\n";
echo "                <img src=\"images/MADELEINE_1.jpg\" />\n";
echo "                <p class=\"lead\">Madeleine<br />Instructor</p>\n";
echo "                <p>Madeleine works directly with remote students.  She has a background in customer service as well as a degree in literature. She's a wonderful addition to our team and enjoys helping students understand new concepts.</p>\n";
echo "            </div>\n";
echo "            <div class=\"col-lg-4 slideanim\">\n";
echo "                <img src=\"images/DANNY_1.jpg\" />\n";
echo "                <p class=\"lead\">Danny<br />Job Placement Director</p>\n";
echo "                <p>Danny has an outgoing personality and experience in web development. He has experience in public relations and networking, and utilizes these skills in assisting students to land jobs. Throughout the program, Danny oversees the placement of students and graduates, helping however he can. He is one of the contributing factors behind The Tech Academy’s 100% job placement rate.\n";
echo "</p>\n";
echo "            </div>\n";
echo "        </div><!-- End Row 4 -->\n";
echo "        \n";
echo "        <div class=\"row tiles\"><!-- Start Row 5 -->\n";
echo "            <div class=\"col-lg-4 slideanim\">\n";
echo "                <img src=\"images/NANCY_1.jpg\" />\n";
echo "                <p class=\"lead\">Nancy<br />Executive Assistant</p>\n";
echo "                <p>Nancy is a professional artist and expert at organization. She possesses incredible persistence and attention to detail. She assists with various internal programs at The Tech Academy. Her friendly attitude and helpfulness is a welcomed aspect of The Tech Academy team. \n";
echo "</p>\n";
echo "            </div>\n";
echo "            <div class=\"col-lg-4 slideanim\">\n";
echo "                <img src=\"images/MICHELLE_1.jpg\" />\n";
echo "                <p class=\"lead\">Michelle<br />Instructor</p>\n";
echo "                <p>Michelle works closely with all students to ensure they have everything they need. If a student issue comes up, she is right there on the ball to get it resolved rapidly. Although Michelle already has a background in programming, she is also moving through our program herself.</p>\n";
echo "            </div>\n";
echo "            <div class=\"col-lg-4 slideanim\">\n";
echo "                <img src=\"images/RICK_2.jpg\" />\n";
echo "                <p class=\"lead\">Rick<br />Instructor</p>\n";
echo "                <p>Rick is a skilled programmer and has experience in assisting others through our program. He really enjoys the work environment and being around others that are just as passionate about technology as he is. He is a caring person that truly enjoys helping people.</p>\n";
echo "            </div>\n";
echo "        </div><!-- End Row 5 -->\n";
echo "        \n";
echo "        <div class=\"row tiles\"><!-- Start Row 6 -->\n";
echo "            <div class=\"col-lg-4 slideanim\">\n";
echo "                <img src=\"images/MICHAEL_1.jpg\" />\n";
echo "                <p class=\"lead\">Michael<br />Remote Job Placement Director</p>\n";
echo "                <p>Michael is our Remote Job Placement Director. He has a real passion and drive for connecting with our remote students and ensuring they get the best job possible once they graduate. Michael is a great \"people’s person\" and is always thinking up ways we can better keep track of and help our students. His work with remote students, is a key contributing factor to our 100% job placement rate.</p>\n";
echo "            </div>\n";
echo "            <div class=\"col-lg-4 slideanim\">\n";
echo "                <img src=\"images/JENNA_1.jpg\" />\n";
echo "                <p class=\"lead\">Jenna<br />Instructor</p>\n";
echo "                <p>Jenna is a gifted coder and loves to help others.  She is from Hawaii and has a background in  tutoring C++. She loves the challenge with helping other students get through their study materials. </p>\n";
echo "            </div>\n";
echo "            <div class=\"col-lg-4 slideanim\">\n";
echo "                <!--<img src=\"images/\" />\n";
echo "                <p class=\"lead\">Name<br />Position</p>\n";
echo "                <p>Blurb</p>-->\n";
echo "            </div>\n";
echo "        </div><!-- End Row 5 -->\n";
echo "        \n";
echo "        <p class=\"lead\">If you have any questions regarding our staff or program, please <a href=\"contact.html\">contact us</a>.</p>\n";
echo "\n";
echo "        <!-- <div class=\"banner row\">\n";
echo "                <h3>15 week Software Developer Boot Camp</h3>\n";
echo "                <h2><a href=\"contact.html\">Enroll Now and START TODAY</a></h2>\n";
echo "        </div> -->\n";
echo "    \n";
echo "\n";
echo "    <!--  Site footer  -->\n";

include 'footer.php';

echo "    \n";
echo "    </div> <!-- /container -->\n";
echo "\n";
echo "    <div id=\"myModalPopUp\" class=\"modal fade\" role=\"dialog\"> <!-- modal dialog box -->\n";
echo "	    <div class=\"modal-dialog\">\n";
echo "		    <!-- Modal content-->\n";
echo "		    <div class=\"modal-content\">\n";
echo "			    <div class=\"modal-header\">\n";
echo "				    <button type=\"button\" class=\"close\" data-dismiss=\"modal\">×</button>\n";
echo "				    <h3 class=\"modal-title\">Hi there!</h3>\n";
echo "			    </div>\n";
echo "			    <div class=\"modal-body\">\n";
echo "				    <p>Would you like to learn more about The Tech Academy?</p>\n";
echo "			    </div>\n";
echo "			    <div class=\"modal-footer\">\n";
echo "                    <a class=\"btn modal-button-yes\" href=\"contact.html\">Yes</a>\n";
echo "                    <a class=\"btn\" data-dismiss=\"modal\">No</a>\n";
echo "			    </div>\n";
echo "		    </div>\n";
echo "	    </div>\n";
echo "    </div>\n";
echo "	\n";
echo "	<!-- Start Alexa Certify Javascript -->\n";
echo "<script type=\"text/javascript\">\n";
echo "_atrk_opts = { atrk_acct:\"jT90m1a8FRh2cN\", domain:\"learncodinganywhere.com\",dynamic: true};\n";
echo "(function() { var as = document.createElement('script'); as.type = 'text/javascript'; as.async = true; as.src = \"https://d31qbv1cthcecs.cloudfront.net/atrk.js\"; var s = document.getElementsByTagName('script')[0];s.parentNode.insertBefore(as, s); })();\n";
echo "</script>\n";
echo "<noscript><img src=\"https://d5nxst8fruw4z.cloudfront.net/atrk.gif?account=jT90m1a8FRh2cN\" style=\"display:none\" height=\"1\" width=\"1\" alt=\"\" /></noscript>\n";
echo "<!-- End Alexa Certify Javascript -->  \n";
echo "\n";
echo "    <script src=\"https://code.jquery.com/jquery-2.1.4.min.js\"></script>\n";
echo "    <script src=\"js/bootstrap.min.js\"></script>\n";
echo "    <script src=\"js/npm.js\"></script>\n";
echo "\n";
echo "    <script>\n";
echo "        $(document).ready(function () {\n";
echo "            function waitThenDoSomething(waitTimeInMS, myAction) {\n";
echo "                setTimeout(function () {\n";
echo "                    if (myAction == \"displayPopup\") {\n";
echo "                        $('#myModalPopUp').modal('show');\n";
echo "                    }\n";
echo "                }, waitTimeInMS); //time in ms to wait before modal dialog box shows up.\n";
echo "            }\n";
echo "            if (document.referrer == \"http://learncodinganywhere.com/index.html\" || document.referrer == \"http://learncodinganywhere.com/\") {\n";
echo "                waitThenDoSomething(0, \"displayPopup\"); //this function waits 0 milliseconds before displaying a popup.\n";
echo "                //I left the wait function here so that if you change your mind and decide you want to wait before showing \n";
echo "                //the modal dialog box, it's as easy as changing the 0 above to a different number, rather than recoding \n";
echo "                //all of it again.\n";
echo "            }\n";
echo "            $(window).ready(function () { $(window).scroll() });\n";
echo "            $(window).scroll(function () {\n";
echo "                $(\".slideanim\").each(function () {\n";
echo "                    var pos = $(this).offset().top;\n";
echo "\n";
echo "                    var winTop = $(window).scrollTop();\n";
echo "                    if (pos < winTop + $(window).height()) {\n";
echo "                        $(this).addClass(\"slide\");\n";
echo "                    }\n";
echo "                });\n";
echo "            });\n";
echo "        });\n";
echo "    </script>\n";
echo "</body>\n";
echo "</html>\n";

?>

