<?php

echo "<!DOCTYPE html>\n";
echo "<html lang=\"en\">\n";
echo "<head>\n";
echo "    <meta charset=\"utf-8\">\n";
echo "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n";
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n";
echo "    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\n";
echo "    <meta name=\"description\" content=\"\">\n";
echo "    <meta name=\"author\" content=\"\">\n";
echo "\n";
echo "    <title>Testimonials</title>\n";
echo "	\n";
echo "	<!--  Font Awesome  -->\n";
echo "	<link href=\"fonts/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\">\n";
echo "	<link href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css\" rel=\"stylesheet\">\n";
echo "	\n";
echo "	<!--  Google Font  -->\n";
echo "	<link href=\"https://fonts.googleapis.com/css?family=Titillium+Web\" rel=\"stylesheet\" type=\"text/css\">\n";
echo "\n";
echo "    <!-- Bootstrap core CSS -->\n";
echo "    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\n";
echo "\n";
echo "    <!-- Custom CSS -->\n";
echo "    <link href=\"css/style.css\" rel=\"stylesheet\">\n";
echo "\n";
echo "\n";
echo "    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\n";
echo "    <!--[if lt IE 9]>\n";
echo "    <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\n";
echo "    <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\n";
echo "    <![endif]-->\n";
echo "</head>\n";
echo "\n";
echo "<body class=\"text-center stories\">\n";
echo "\n";
echo "    <div class=\"container\">\n";
echo "\n";
echo "        <!--  The justified navigation menu is meant for single line per list item.\n";
echo "        Multiple lines will require custom code not provided by Bootstrap.  -->\n";

include 'header.php';

echo "       \n";
echo "        <h2>Graduate Success Stories</h2>\n";
echo "\n";
echo "        <!-- Start Tiles -->\n";
echo "        <div class=\"row tiles slideanim\"><!-- Start Row 1 -->\n";
echo "            <a name=\"cole\"></a>\n";
echo "            <div class=\"col-lg-4 testimonial img1\" id=\"img_1\">\n";
echo "                <blockquote>\"Each course is beautifully developed on an incrementing scale of difficulty to fully immerse the student in possible real-world scenarios…”</blockquote>\n";
echo "            </div>\n";
echo "            <div class=\"col-lg-8 text-justify\">\n";
echo "                <p>“I have always had a voracious appetite for knowledge across a vast myriad of different subjects and genres. Coding was never something that even pinged on my radar as a possible career avenue. It was not until I heard of the unique environment and learning structure at the Tech Academy that I felt inclined to look into the technology field. As I researched all of the diverse code schools that the Portland area had to offer, word kept coming around about how intentionally different the Tech Academy was in its approach to teaching the fundamentals of software development.</p>\n";
echo "                <p id=\"location_1\">“Upon my acceptance to Tech Academy and initial introduction to the course material, I knew I had made the correct choice. Each course is beautifully developed on an incrementing scale of difficulty to fully immerse the student in possible real-world scenarios and deeply instill the vocabulary and syntax of each coding language and OOP. With a range of interests from front-end to back-end and database implementation, everything needed to be successful in the industry is covered.</p>\n";
echo "                <p>“Working through drills and projects that are specifically designed to test your skills and creativity one gains an incredibly in-depth knowledge of each language they are working in. I had the privilege of not only being a student but also being an employee of the Tech Academy.</p>\n";
echo "                <p>“The team that Erik and Jack have assembled to instruct and mentor students is a cut above. They truly are the heart of the program and have an eagerness and thirst for knowledge that is demonstrated through their teachings.</p>\n";
echo "                <p>“If it were not for the skills gleaned from study and participation in all of the events and lectures Tech Academy offers, I would not have earned the job I have been offered. Participating in Tech Talks, weekly Career Round Table sessions, and meet-ups is essential to understanding the layout of the tech industry and pushing through all of the doors marked pull.\n";
echo "</p>\n";
echo "                <p>“I would like to extend a most gracious ‘thank you’ to the staff and all of the student body, [both remote and local], for making my time at the Tech Academy full of meaningful interactions, immersive conversations, inventive challenges, and a lot of memories and knowledge that I will carry with me into my new career in Colorado.”</p>\n";
echo "                <p class=\"text-right\">-Cole D.</p>\n";
echo "            </div>   \n";
echo "        </div><!-- End Row 1 --><hr />\n";
echo "        \n";
echo "        <div class=\"row tiles slideanim\"><!-- Start Row 2 -->\n";
echo "            <a name=\"nick\"></a>\n";
echo "            <div class=\"col-lg-8 text-justify\">\n";
echo "                \n";
echo "                <p>“Ever since I was young, I always had a fascination with computers and software. It started with a Visual Basic game programming book I picked up at the store when I was 10, and just spiraled out of control from there. I read everything I could get my hands on, started doing little projects in all my free time, attended summer camps specifically for programming. My life has basically always, in some way, revolved around software for the past 12 years. \n";
echo "</p>\n";
echo "                <p id=\"location_2\">“This past year when college wasn't quite working out for me, I decided to pack up, and move from Atlanta to Portland in early January. I started at the Tech Academy as soon as I arrived. I knew I had the skills to break into the industry, but with my partial college background, and limited formal experience, I felt like I could benefit from the training and connections at The Tech Academy. One of the things I really enjoyed most about The Tech Academy was the self-paced learning structure. </p>\n";
echo "                <p>“I personally consume information quickly, and when I throw myself at something, it kind of consumes my life. I threw myself at the program for up to 10 hours a day, almost every day of the week, living and breathing code. I came into the office as often as I could, and just worked until I either felt like I'd hit a roadblock and needed some time to think, or felt like passing out. If you're going to be going through this program, I recommend you take the same approach. </p>\n";
echo "                <p>“I've never really dived too far into .NET, there's a lot of information regarding the framework, and it's tough to pick a place to start. But the way information was presented made it easy to digest, especially for an experienced developer like myself. I got a much better grasp on databases, ASP.NET, LINQ, agile development fundamentals, GIT, and even python. I graduated with an MTA certification, and a lot of the holes in my self-training over the years were filled. As a developer, I'm much more confident today than I was just two short months ago. </p>\n";
echo "                <p>“I quickly jumped into a few live projects a few weeks after starting, which consisted of live development work on paid projects. These projects directly related to the job I ended up getting at a company specializing in data acquisition and web services. When I described the skills I used on these projects in my interview with the company, they were extremely impressed that someone as young as me had worked with the specific technologies and skills used to complete these live projects.</p>\n";
echo "                <p>“If you're a self-motivated individual that truly has a passion for software, with tons or little to no experience, and you're looking to get paid for your developer skills, I cannot recommend The Tech Academy enough. Just a few weeks ago I was a transplant in Portland, with no connections, no job, no plans, nothing. Now, I've got a 60k a year job with full benefits, working at an amazing company, in a beautiful office in downtown Portland, with the latest technologies as a junior software developer. I got exactly what I wanted out of this experience, and I couldn't recommend it enough to anyone looking to follow a similar path.\" </p>\n";
echo "                <p class=\"text-right\">-Nick J.</p>\n";
echo "            </div>  \n";
echo "            <div class=\"col-lg-4 testimonial img2\" id=\"img_2\">\n";
echo "                <blockquote>“I cannot recommend The Tech Academy enough… I’ve got a 60k a year job with full benefits, working at an amazing company, in a beautiful office in downtown Portland…”</blockquote>\n";
echo "            </div>\n";
echo "             \n";
echo "        </div><!-- End Row 2 --><hr />\n";
echo "\n";
echo "        <div class=\"row tiles slideanim\"><!-- Start Row 3 -->\n";
echo "            <a name=\"neil\"></a>\n";
echo "            <div class=\"col-lg-4 testimonial img3\" id=\"img_3\">\n";
echo "                <blockquote>“The curriculum was very comprehensive and I liked that it covered complicated concepts like object oriented programming and databases, and wasn’t \n";
echo "				limited to just learning a handful of simpler Web-based languages.”</blockquote>\n";
echo "            </div>\n";
echo "            <div class=\"col-lg-8 text-justify\">\n";
echo "                <p>\"Studying at The Tech Academy was a great experience, and was a big key in reaching my goals of learning a lot about software development, understanding object oriented programming, and landing a job at an awesome software company in Portland. I began the program with a fair amount of computer knowledge, which helped me get through the first few courses pretty quickly. Understanding how to work with databases, code in Python, and especially grasp the concepts of C# programming was no easy task, but the course material and assistance from the instructors and other students helped me break through and comprehend them.</p> \n";
echo "				<p id=\"location_3\">There is a vast, vast amount of knowledge to be understood in just a few months of study, and the school's method of starting out with the basics and building on that with each course made it easier. Being in this learning environment 8 hours a day for 5 days a week was certainly helpful -- however, I really liked the flexibility of schedule that the school allows, as some of it can be done off site. When I started, I was still working full time, and studying in the evenings, so I appreciated having this option. I particularly found the coding drills to be the best learning tools in the program. They were challenging and really made me think and learn by jumping in and coding, which is the best way to learn how to code. I thought the Live Project was awesome, and developing a real-world web site project as a team was a great way to learn from other students as well as contribute to a project.</p>\n";
echo "                <p>“The curriculum was very comprehensive and I liked that it covered complicated concepts like object oriented programming and databases, and wasn't limited to just learning a handful of simpler Web-based languages. I liked that I was challenged frequently, and was often stuck, but help was always available when I couldn't figure something out. I found the C# drills to be particularly challenging, and helped me the most when I went to take the MTA exam. When I first walked into the school, there’s no way I could have passed the exam. Taking the exam and answering the questions correctly made me realize how much I've learned over the past few months. Overall, I am happy with my experience at the school and feel that I have a strong foundation of knowledge and skills that will benefit me throughout my career in the software industry.\"</p>\n";
echo "                <p class=\"text-right\">-Neil T.</p>\n";
echo "            </div>   \n";
echo "        </div><!-- End Row 3 --><hr />\n";
echo "        \n";
echo "        <div class=\"row tiles slideanim\"><!-- Start Row 4 -->\n";
echo "            <!--<p class=\"lead text-center\"></p>-->\n";
echo "            <div class=\"col-lg-8 text-justify\">\n";
echo "                \n";
echo "                <p>\"I can't recommend The Tech Academy enough. I have 17 years of Software Quality Experience and was faced with a career path that had changed dramatically after I became gainfully unemployed. The need to be familiar with code had changed to actually having to be able to code. </p>\n";
echo "				<p id=\"location_4\">Automation had taken the forefront as companies embraced agile methodologies. After failing a few job interviews because of my lack of working knowledge in coding I decided to bite the bullet and start the learning process. I saw the adds for The Portland Tech  Academy and after talking with Erik over the phone and in person I chose them based on their curriculum and level of commitment to their students. As I neared the completion of the training I updated my resume with my current course work and started to apply to some jobs. I had 7 interviews in 2 weeks and 5 offers came out of them. The only reason this happened is because I had the knowledge and the confidence to continually 'knock the ball out of the park.' I gained that confidence and knowledge at The Portland Tech Academy and you should too.\" \n";
echo "</p>\n";
echo "                <p class=\"text-right\">-Johnny R.</p>\n";
echo "            </div>  \n";
echo "            <div class=\"col-lg-4 testimonial img4\" id=\"img_4\">\n";
echo "                <blockquote>\"I had 7 interviews in 2 weeks and 5 offers came out of them. The only reason this happened is because I had the knowledge and the confidence to continually 'knock the ball out of the park.'\"</blockquote>\n";
echo "            </div>\n";
echo "             \n";
echo "        </div><!-- End Row 4 -->\n";
echo "\n";
echo "        <div class=\"row tiles slideanim\"><!-- Start Row 5 -->\n";
echo "            <!--<p class=\"lead text-center\"></p>-->\n";
echo "            <div class=\"col-lg-4 testimonial img5\" id=\"img_6\">\n";
echo "                <blockquote>“I was able to secure a job in software development before graduating.”</blockquote>\n";
echo "            </div>\n";
echo "            <div class=\"col-lg-8 text-justify\">\n";
echo "                <p>\"I had been out of the computer science field for 9 years. My family was at the point that I needed to change jobs and make more money. Going back to traditional schooling didn't make sense. We could not afford it and to put it on a loan would be moving backwards. That's when I found The Tech Academy.</p> \n";
echo "				<p id=\"location_6\">The coursework was in depth and provided the base I needed to reintegrate myself into the computing field. The instructors are friendly and helpful and make sure you have a clear understanding of the material. I was able to secure a job in software development before graduating. I highly recommend them to anyone looking to make a change or who just wants to break into the computer industry.\" \n";
echo "</p>\n";
echo "                <p class=\"text-right\">-Matt A.</p>\n";
echo "            </div>   \n";
echo "        </div><!-- End Row 5 -->\n";
echo "        \n";
echo "        <div class=\"row tiles slideanim\"><!-- Start Row 6 -->\n";
echo "            <!--<p class=\"lead text-center\"></p>-->\n";
echo "            \n";
echo "            <div class=\"col-lg-8 text-justify\">\n";
echo "                <p>\"I came to The Tech Academy already a software engineer. It's been a few years since I've used C# and .Net and wanted some refresher on Microsoft technologies. I also found the coursework covered areas other boot camps don't. During my time there I got a bit more comfortable with MVC and LINQ both of which I had limited experience with. There were several Oh yeah! moments in the C# course where different concepts came back to me. I also really enjoyed learning Python. It's an impressively powerful language that greatly simplifies writing code.</p> \n";
echo "				<p id=\"location_7\">Despite being more of a night owl, I also enjoyed the chats with other students and the help I received from Alem and Brett, both excellent people! One of the most important things I've learned is that software itself is not a goal. There is so much to learn and know that it's impossible for one person to do it all.</p>\n";
echo "                <p>The first course reminded me what software's roots are. It's easy to get caught up in the latest language or framework, but it's all underpinned with binary. Those fundamentals are important as languages and frameworks continue to abstract away the mechanics of computation. Each course at The Tech Academy builds on concepts from the previous in a way that guides students in a soup-to-nuts path. Where the landscape of learning software is broad and meandering, The Tech Academy has put together a concise efficient program that guides students to an impressive level of functioning right out of the gate. I'd like to say thank you to everyone at The Tech Academy for being who you are, great people, with great vision and continued success.\"</p>\n";
echo "                <p class=\"text-right\">-Robert A.</p>\n";
echo "            </div>   \n";
echo "            <div class=\"col-lg-4 testimonial img6\" id=\"img_7\">\n";
echo "                <blockquote>“Where the landscape of learning software is broad and meandering, The Tech Academy has put together a concise efficient program that guides students to an impressive level of functioning right out of the gate.”</blockquote>\n";
echo "            </div>\n";
echo "        </div><!-- End Row 6 -->\n";
echo "        \n";
echo "        <div class=\"row tiles slideanim\"><!-- Start Row 7 -->\n";
echo "            <!--<p class=\"lead text-center\"></p>-->\n";
echo "            <div class=\"col-lg-4 testimonial img7\" id=\"img_5\">\n";
echo "                <blockquote>“I looked at the offerings of several boot camps in the area, and found that the Tech Academy offered the strongest curriculum towards a path in software development.”</blockquote>\n";
echo "            </div>\n";
echo "            <div class=\"col-lg-8 text-justify\">\n";
echo "                <p>\"Before coming to the Tech Academy I had been trying for the past year to change career fields from engineering to the tech industry. I had some programming knowledge, and was able to get a few interviews, but my skills were never quite strong enough to seal the deal and get a job offer. I had investigated some online degree programs, but the length of time and the cost were both higher than I was willing to spend. That was when I found the Tech Academy. </p>\n";
echo "				<p id=\"location_5\">I looked at the offerings of several boot camps in the area, and found that the Tech Academy offered the strongest curriculum towards a path in software development. I then left my engineering position to pursue instruction at the Tech Academy full time, and have had absolutely no regrets. The instructors have been attentive and helpful, and I have been able to master the skills I was seeking to enter the tech industry. I would highly recommend the Tech Academy to anyone seeking quick entry into software development.\"</p>\n";
echo "                <p class=\"text-right\">-Daniel H.</p>\n";
echo "            </div>   \n";
echo "        </div><!-- End Row 7 -->\n";
echo "        \n";
echo "        <div class=\"row tiles slideanim\"><!-- Start Row 8 -->\n";
echo "            <!-- <div class=\"col-lg-2\">\n";
echo "            </div> -->\n";
echo "            <div class=\"col-lg-12\">\n";
echo "                <p class=\"lead\">Also, here is a short Student Testimonial video that we threw together:</p>\n";
echo "				\n";
echo "				<iframe width=\"853\" height=\"480\" src=\"https://www.youtube.com/embed/hT-S3Smjdrk\"  id=\"iframeOtherPages\" frameborder=\"0\" allowfullscreen></iframe>\n";
echo "                \n";
echo "                <p>For more student successes, please visit our <a href=\"https://www.facebook.com/The-Tech-Academy-663002590387052/\" target=\"_blank\">Facebook page</a>.</p>\n";
echo "                <p>To inquire, please feel free to <a href=\"contact.html\">contact us</a>.</p>\n";
echo "            </div>  \n";
echo "            <div class=\"col-lg-2\">\n";
echo "            </div>\n";
echo "        </div><!-- End Row 8 -->\n";
echo "        \n";
echo "        <!-- <div class=\"banner row\">\n";
echo "                <h3>15 week Software Developer Boot Camp</h3>\n";
echo "                <h2><a href=\"contact.html\">Enroll Now and START TODAY</a></h2>\n";
echo "        </div> -->\n";
echo "    \n";
echo "\n";
echo "    <!--  Site footer  -->\n";
include 'footer.php';
echo "    \n";
echo "\n";
echo "    </div> <!-- /container -->\n";
echo "    <div id=\"myModalPopUp\" class=\"modal fade\" role=\"dialog\"> <!-- modal dialog box -->\n";
echo "	    <div class=\"modal-dialog\">\n";
echo "		    <!-- Modal content-->\n";
echo "		    <div class=\"modal-content\">\n";
echo "			    <div class=\"modal-header\">\n";
echo "				    <button type=\"button\" class=\"close\" data-dismiss=\"modal\">×</button>\n";
echo "				    <h3 class=\"modal-title\">Hi there!</h3>\n";
echo "			    </div>\n";
echo "			    <div class=\"modal-body\">\n";
echo "				    <p>Would you like to learn more about The Tech Academy?</p>\n";
echo "			    </div>\n";
echo "			    <div class=\"modal-footer\">\n";
echo "                    <a class=\"btn modal-button-yes\" href=\"contact.html\">Yes</a>\n";
echo "                    <a class=\"btn\" data-dismiss=\"modal\">No</a>\n";
echo "			    </div>\n";
echo "		    </div>\n";
echo "	    </div>\n";
echo "    </div>\n";
echo "\n";
echo "	<!-- Start Alexa Certify Javascript -->\n";
echo "<script type=\"text/javascript\">\n";
echo "_atrk_opts = { atrk_acct:\"jT90m1a8FRh2cN\", domain:\"learncodinganywhere.com\",dynamic: true};\n";
echo "(function() { var as = document.createElement('script'); as.type = 'text/javascript'; as.async = true; as.src = \"https://d31qbv1cthcecs.cloudfront.net/atrk.js\"; var s = document.getElementsByTagName('script')[0];s.parentNode.insertBefore(as, s); })();\n";
echo "</script>\n";
echo "<noscript><img src=\"https://d5nxst8fruw4z.cloudfront.net/atrk.gif?account=jT90m1a8FRh2cN\" style=\"display:none\" height=\"1\" width=\"1\" alt=\"\" /></noscript>\n";
echo "<!-- End Alexa Certify Javascript -->  \n";
echo "\n";
echo "    <script src=\"https://code.jquery.com/jquery-2.1.4.min.js\"></script>\n";
echo "    <script src=\"js/bootstrap.min.js\"></script>\n";
echo "    <script src=\"js/npm.js\"></script>\n";
echo "	\n";
echo "	<script>\n";
echo "		$(document).ready(function() {\n";
echo "			var w = Math.max(document.documentElement.clientWidth, window.innerWidth || 0);\n";
echo "			if (w <657) {\n";
echo "				$('#img_1').insertBefore('#location_1');\n";
echo "				$('#img_2').insertBefore('#location_2');\n";
echo "				$('#img_3').insertBefore('#location_3');\n";
echo "				$('#img_4').insertBefore('#location_4');\n";
echo "				$('#img_5').insertBefore('#location_5');\n";
echo "				$('#img_6').insertBefore('#location_6');\n";
echo "				$('#img_7').insertBefore('#location_7');\n";
echo "			}\n";
echo "			function waitThenDoSomething(waitTimeInMS, myAction) {\n";
echo "			    setTimeout(function () {\n";
echo "			        if (myAction == \"displayPopup\") {\n";
echo "			            $('#myModalPopUp').modal('show');\n";
echo "			        }\n";
echo "			    }, waitTimeInMS); //time in ms to wait before modal dialog box shows up.\n";
echo "			}\n";
echo "			if (document.referrer == \"http://learncodinganywhere.com/index.html\" || document.referrer == \"http://learncodinganywhere.com/\") {\n";
echo "			    waitThenDoSomething(0, \"displayPopup\"); //this function waits 0 milliseconds before displaying a popup.\n";
echo "			    //I left the wait function here so that if you change your mind and decide you want to wait before showing \n";
echo "			    //the modal dialog box, it's as easy as changing the 0 above to a different number, rather than recoding \n";
echo "			    //all of it again.\n";
echo "			}\n";
echo "			$(window).ready(function () { $(window).scroll() });\n";
echo "			$(window).scroll(function () {\n";
echo "			    $(\".slideanim\").each(function () {\n";
echo "			        var pos = $(this).offset().top;\n";
echo "\n";
echo "			        var winTop = $(window).scrollTop();\n";
echo "			        if (pos < winTop + $(window).height()) {\n";
echo "			            $(this).addClass(\"slide\");\n";
echo "			        }\n";
echo "			    });\n";
echo "			});\n";
echo "		});\n";
echo "		\n";
echo "			\n";
echo "	</script>\n";
echo "</body>\n";
echo "</html>\n";

?>

